select fn_db_update_config_value('AdminPassword','letmein!','general');
select fn_db_update_config_value('CABaseDirectory','ca','general');
select fn_db_update_config_value('CertAlias','1','general');
select fn_db_update_config_value('CertificateFileName','certs/engine.cer','general');
select fn_db_update_config_value('ENGINEEARLib','%JBOSS_HOME%/server/engine-slimmed/deploy/engine.ear','general');
select fn_db_update_config_value('InstallVds', 'false','general');
select fn_db_update_config_value('SSLEnabled', 'false','general');
select fn_db_update_config_value('SysPrep2K3Path','backend/manager/conf/sysprep/sysprep.2k3');
select fn_db_update_config_value('SysPrep2K8Path','backend/manager/conf/sysprep/sysprep.2k8');
select fn_db_update_config_value('SysPrep2K8R2Path','backend/manager/conf/sysprep/sysprep.2k8');
select fn_db_update_config_value('SysPrep2K8x64Path','backend/manager/conf/sysprep/sysprep.2k8x86');
select fn_db_update_config_value('SysPrepWindows7Path','backend/manager/conf/sysprep/sysprep.w7');
select fn_db_update_config_value('SysPrepWindows7x64Path','backend/manager/conf/sysprep/sysprep.w7x64');
select fn_db_update_config_value('SysPrepXPPath','backend/manager/conf/sysprep/sysprep.xp');
select fn_db_update_config_value('UseSecureConnectionWithServers', 'false','general');
select fn_db_update_config_value('keystorePass','NoSoup4U','general');
select fn_db_update_config_value('keystoreUrl','keys/engine.p12','general');
