-- Function definition script SWF_Execute for PostgreSQL
-- Generated by (c) Ispirer SQLWays 4.0 Build 436 Licensed to Red Hat
-- Timestamp: Fri Jan 14 13:23:57 2011

CREATE OR REPLACE FUNCTION SWF_Execute(TEXT)
RETURNS VOID 
AS $$ BEGIN EXECUTE $1; END; $$ 
LANGUAGE plpgsql;
;

