#!/bin/sh

#compress log4j log files, delete old ones
/usr/share/ovirt/scripts/ovirtlogrot.sh /var/log/ovirt-engine 480 > /dev/null

EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t rhevm "ALERT exited abnormally with [$EXITVALUE]"
fi
exit $EXITVALUE

