package org.ovirt.engine.ui.frontend;

import com.google.gwt.i18n.client.ConstantsWithLookup;

public interface AppErrors extends ConstantsWithLookup {
    String MAC_POOL_NOT_ENOUGH_MAC_ADDRESSES();

    String ACTION_TYPE_FAILED_CANNOT_REMOVE_STILL_USED_MAC_POOL();

    String VAR__ENTITIES__CLUSTERS();

    String ACTION_TYPE_FAILED_CANNOT_REMOVE_DEFAULT_MAC_POOL();

    String ACTION_TYPE_FAILED_MAC_POOL_DOES_NOT_EXIST();

    String ACTION_TYPE_FAILED_CHANGING_DEFAULT_MAC_POOL_IS_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_SETTING_DEFAULT_MAC_POOL_IS_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_MAC_POOL_MUST_HAVE_RANGE();

    String ACTION_TYPE_FAILED_INVALID_PUBLIC_SSH_KEY();

    String VMT_CANNOT_REMOVE_DETECTED_DERIVED_VM();

    String VMT_CANNOT_REMOVE_BASE_WITH_VERSIONS();

    String ACTION_TYPE_FAILED_DETECTED_DERIVED_DISKS();

    String ACTION_TYPE_FAILED_DISKS_SNAPSHOTS_DONT_BELONG_TO_SAME_DISK();

    String ACTION_TYPE_FAILED_VM_SNAPSHOT_HAS_UNPLUGGED_OR_UNATTACHED_DISKS();

    String ACTION_TYPE_FAILED_VM_IMAGE_DOES_NOT_EXIST();

    String ACTION_TYPE_FAILED_VM_SNAPSHOT_DOES_NOT_EXIST();

    String ACTION_TYPE_FAILED_VM_SNAPSHOT_TYPE_NOT_REGULAR();

    String ACTION_TYPE_FAILED_CORRUPTED_VM_SNAPSHOT_ID();

    String ACTION_TYPE_FAILED_LEASE_DOMAIN_ID_IS_NOT_VALID();

    String ACTION_TYPE_FAILED_VM_SNAPSHOT_HAS_NO_CONFIGURATION();

    String ACTION_TYPE_FAILED_DISK_HAS_SNAPSHOTS();

    String ACTION_TYPE_FAILED_CANNOT_RUN_ACTION_ON_NON_MANAGED_VM();

    String ACTION_TYPE_FAILED_MIN_MEMORY_CANNOT_EXCEED_MEMORY_SIZE();

    String ACTION_TYPE_FAILED_MIN_MEMORY_CANNOT_BE_NEGATIVE();

    String ACTION_TYPE_FAILED_MAX_MEMORY_CANNOT_BE_SMALLER_THAN_MEMORY_SIZE();

    String ACTION_TYPE_FAILED_PHYSICAL_MEMORY_CANNOT_BE_SMALLER_THAN_MEMORY_SIZE();

    String ACTION_TYPE_FAILED_MAX_MEMORY_CANNOT_EXCEED_PLATFORM_LIMIT();

    String ACTION_TYPE_FAILED_VM_DISKS_ON_BACKUP_STORAGE();

    String ACTION_TYPE_FAILED_DOMAIN_TYPE_DOES_NOT_SUPPORT_BACKUP();

    String VM_TEMPLATE_IS_LOCKED();

    String VM_TEMPLATE_WITH_CLUSTER_WITHOUT_BIOS_TYPE();

    String VM_TEMPLATE_WITHOUT_CLUSTER_WITH_BIOS_TYPE();

    String VM_TEMPLATE_IMAGE_IS_LOCKED();

    String VM_TEMPLATE_IMAGE_IS_ILLEGAL();

    String VM_TEMPLATE_IMAGE_LAST_DOMAIN();

    String VM_CANNOT_UPDATE_ILLEGAL_FIELD();

    String VM_CANNOT_UPDATE_HOSTED_ENGINE_FIELD();

    String VM_CANNOT_RUN_FROM_NETWORK_WITHOUT_NETWORK();

    String VM_CANNOT_RUN_FROM_CD_WITHOUT_ACTIVE_STORAGE_DOMAIN_ISO();

    String VM_CANNOT_RUN_FROM_DISK_WITHOUT_DISK();

    String VM_CANNOT_RUN_STATELESS_WHILE_IN_PREVIEW();

    String VM_CANNOT_RUN_STATELESS_HA();

    String ACTION_TYPE_FAILED_DELETE_PROTECTION_ENABLED();

    String USER_CANNOT_REMOVE_HIMSELF();

    String VDS_CANNOT_MAINTENANCE_VDS_IS_NOT_RESPONDING_WITH_VMS();

    String VDS_CANNOT_MAINTENANCE_VDS_IS_NOT_RESPONDING_AND_IS_SPM();

    String VDS_CANNOT_MAINTENANCE_VDS_IS_NOT_OPERATIONAL();

    String VDS_CANNOT_MAINTENANCE_VDS_IS_IN_MAINTENANCE();

    String VDS_CANNOT_MAINTENANCE_VDS_HAS_AFFINITY_VMS();

    String VDS_CANNOT_MAINTENANCE_HOST_WITH_RUNNING_IMAGE_TRANSFERS();

    String CPU_TYPE_UNSUPPORTED_IN_THIS_CLUSTER_VERSION();

    String ACTION_TYPE_FAILED_VM_CLUSTER_DIFFERENT_ARCHITECTURES();

    String ACTION_TYPE_FAILED_VDS_CLUSTER_DIFFERENT_ARCHITECTURES();

    String ACTION_TYPE_FAILED_HOST_CLUSTER_DIFFERENT_MANAGEMENT_NETWORKS();

    String VDS_CANNOT_MAINTENANCE_SPM_WITH_RUNNING_TASKS();

    String VDS_CANNOT_MAINTENANCE_HOST_WITH_RUNNING_OPERATIONS();

    String VDS_CANNOT_MAINTENANCE_SPM_CONTENDING();

    String VDS_CANNOT_MAINTENANCE_NO_ALTERNATE_HOST_FOR_HOSTED_ENGINE ();

    String VDS_CANNOT_MAINTENANCE_IT_INCLUDES_NON_MIGRATABLE_VM();

    String VDS_CANNOT_MAINTENANCE_GLUSTER_QUORUM_CANNOT_BE_MET();

    String VDS_CANNOT_MAINTENANCE_UNSYNCED_ENTRIES_PRESENT_IN_GLUSTER_BRICKS();

    String VDS_CANNOT_MAINTENANCE_VM_HAS_PLUGGED_DISK_SNAPSHOT();

    String ACTION_TYPE_FAILED_UNSUPPORTED_OVF();

    String ACTION_TYPE_FAILED_OVF_DISK_NOT_IN_APPLICABLE_STATUS();

    String VDS_CANNOT_REMOVE_DEFAULT_CLUSTER();

    String VDS_CANNOT_REMOVE_VDS_DETECTED_RUNNING_VM();

    String VDS_CANNOT_REMOVE_CLUSTER_VDS_DETECTED();

    String VDS_CANNOT_REMOVE_VDS_STATUS_ILLEGAL();

    String CANNOT_ENROLL_CERTIFICATE_HOST_STATUS_ILLEGAL();

    String VDS_NOT_EXIST();

    String CANNOT_FORCE_SELECT_SPM_VDS_NOT_UP();

    String CANNOT_FORCE_SELECT_SPM_VDS_ALREADY_SPM();

    String CANNOT_FORCE_SELECT_SPM_VDS_MARKED_AS_NEVER_SPM();

    String CANNOT_FORCE_SELECT_SPM_STORAGE_POOL_HAS_RUNNING_TASKS();

    String CANNOT_FORCE_SELECT_SPM_VDS_NOT_IN_POOL();

    String CANNOT_FORCE_SELECT_SPM_HOST_DOES_NOT_SUPPORT_VIRT_SERVICES();

    String VDS_STATUS_NOT_VALID_FOR_STOP();

    String VDS_STATUS_NOT_VALID_FOR_START();

    String VDS_NO_VDS_PROXY_FOUND();

    String VDS_FAILED_FENCE_VIA_PROXY_CONNECTION();

    String VDS_STATUS_NOT_VALID_FOR_UPDATE();

    String VDS_ALREADY_UP();

    String VDS_NO_UUID();

    String VDS_NON_RESPONSIVE();

    String VDS_DOES_NOT_EXIST();

    String VDS_INVALID_SERVER_ID();

    String VDS_EMPTY_NAME_OR_ID();

    String VDS_CANNOT_INSTALL_EMPTY_PASSWORD();

    String VDS_CANNOT_INSTALL_STATUS_ILLEGAL();

    String VDS_CANNOT_UPGRADE_BETWEEN_MAJOR_VERSION();

    String NO_AVAILABLE_UPDATES_FOR_HOST();

    String CANNOT_UPGRADE_HOST_WITHOUT_OS();

    String CANNOT_UPGRADE_HOST_STATUS_ILLEGAL();

    String CANNOT_UPGRADE_HOST_CLUSTER_CPU_AFFECTED_BY_TSX_REMOVAL();

    String VDS_PORT_CHANGE_REQUIRE_INSTALL();

    String VDS_TRY_CREATE_SECURE_CERTIFICATE_NOT_FOUND();

    String VDS_PROVIDER_PROVISION_MISSING_HOSTGROUP();

    String VDS_PROVIDER_PROVISION_MISSING_COMPUTERESOURCE();

    String VDS_FENCE_DISABLED();

    String VDS_FENCE_DISABLED_AT_SYSTEM_STARTUP_INTERVAL();

    String VDS_FENCE_DISABLED_AT_QUIET_TIME();

    String VDS_FENCE_DISABLED_BY_CLUSTER_POLICY();

    String TEMPLATE_IMAGE_NOT_EXIST();

    String TPM_DEVICE_REQUESTED_ON_NOT_SUPPORTED_PLATFORM();

    String TPM_DEVICE_REQUIRED_BY_OS();

    String VM_CANNOT_REMOVE_CLUSTER_VMS_DETECTED();

    String VMT_CANNOT_REMOVE_CLUSTER_VMTS_DETECTED();

    String CLUSTER_CANNOT_REMOVE_HAS_VM_POOLS();

    String VM_POOL_CANNOT_ADD_VM_WITH_USERS_ATTACHED_TO_POOL();

    String VM_POOL_NOT_FOUND();

    String VM_POOL_CANNOT_ADD_VM_ATTACHED_TO_POOL();

    String VM_POOL_CANNOT_DETACH_VM_NOT_ATTACHED_TO_POOL();

    String VM_POOL_CANNOT_ADD_VM_DIFFERENT_CLUSTER();

    String VM_POOL_CANNOT_REMOVE_RUNNING_VM_FROM_POOL();

    String VM_POOL_CANNOT_ADD_RUNNING_VM_TO_POOL();

    String VMT_CANNOT_CREATE_TEMPLATE_FROM_DOWN_VM();

    String VMT_CANNOT_REMOVE_BLANK_TEMPLATE();

    String VMT_CANNOT_EXPORT_BLANK_TEMPLATE();

    String VMT_CANNOT_UPDATE_ILLEGAL_FIELD();

    String VMT_CANNOT_UPDATE_VERSION_NAME();

    String ACTION_TYPE_FAILED_VM_IN_PREVIEW();

    String ACTION_TYPE_FAILED_STORAGE_DELETE_VMS_IN_PREVIEW();

    String ACTION_TYPE_FAILED_VM_DISK_SNAPSHOT_IS_ATTACHED_TO_ANOTHER_VM();

    String ACTION_TYPE_FAILED_VM_DISK_SNAPSHOT_IS_PLUGGED_TO_ANOTHER_VM();

    String ACTION_TYPE_FAILED_VM_DISK_SNAPSHOT_NOT_ATTACHED_TO_VM();

    String ACTION_TYPE_FAILED_VM_HAS_PLUGGED_DISK_SNAPSHOT();

    String ACTION_TYPE_FAILED_DISK_CONTENT_TYPE_NOT_SUPPORTED_FOR_OPERATION();

    String ACTION_TYPE_FAILED_MEMORY_DISK_SNAPSHOT_IN_PREVIEW();

    String ACTION_TYPE_FAILED_DISK_IS_A_HOSTED_ENGINE_DISK();

    String ACTION_TYPE_FAILED_CANNOT_REMOVE_HIBERNATION_DISK();

    String ACTION_TYPE_FAILED_SHAREABLE_DISKS_NOT_SUPPORTED_ON_GLUSTER_DOMAIN();

    String ACTION_TYPE_FAILED_DISKS_LOCKED();

    String ACTION_TYPE_FAILED_DISK_IS_LOCKED();

    String ACTION_TYPE_DISK_INTERFACE_UNSUPPORTED();

    String ACTION_TYPE_FAILED_DISKS_ILLEGAL();

    String ACTION_TYPE_FAILED_MOVE_DISKS_MIXED_PLUGGED_STATUS();

    String ACTION_TYPE_FAILED_IMPORT_DISKS_ALREADY_EXIST();

    String ACTION_TYPE_FAILED_DUPLICATED_DISK_OR_IMAGE_IDS();

    String ACTION_TYPE_FAILED_CLUSTER_UNDEFINED_ARCHITECTURE();

    String ACTION_TYPE_FAILED_VM_IS_LOCKED();

    String ACTION_TYPE_FAILED_VM_DURING_EXPORT();

    String ACTION_TYPE_FAILED_VM_IMAGE_IS_ILLEGAL();

    String ACTION_TYPE_FAILED_VM_WITH_LOCALDISK_USER_PROPERTY();

    String ACTION_TYPE_FAILED_VM_IS_RUNNING();

    String ACTION_TYPE_FAILED_VM_IS_BEING_CLONED();

    String ACTION_TYPE_FAILED_VM_IS_BEING_UPDATED();

    String ACTION_TYPE_FAILED_VM_IS_NOT_RUNNING();

    String ACTION_TYPE_FAILED_VM_IS_NOT_UP();

    String ACTION_TYPE_FAILED_VM_IS_NOT_DOWN();

    String ACTION_TYPE_FAILED_QCOW_COMPAT_DOES_NOT_MATCH_DC_VERSION();

    String ACTION_TYPE_FAILED_VM_IS_NOT_DOWN_OR_UP();

    String ACTION_TYPE_FAILED_VM_IS_SAVING_RESTORING();

    String ACTION_TYPE_FAILED_VM_IS_DURING_SNAPSHOT();

    String ACTION_TYPE_FAILED_VM_STATUS_ILLEGAL();

    String ACTION_TYPE_FAILED_VM_RUNNING_STATELESS();

    String ACTION_TYPE_FAILED_VM_HAS_STATELESS_SNAPSHOT_LEFTOVER();

    String ACTION_TYPE_FAILED_VM_IN_USE_BY_OTHER_USER();

    String ACTION_TYPE_FAILED_VM_NOT_FOUND();

    String ACTION_TYPE_FAILED_VM_NOT_SET_FOR_LATEST();

    String ACTION_TYPE_FAILED_VM_ALREADY_IN_LATEST_VERSION();

    String ACTION_TYPE_FAILED_VM_IS_NON_MIGRTABLE_AND_IS_NOT_FORCED_BY_USER_TO_MIGRATE();

    String ACTION_TYPE_FAILED_VM_IS_PINNED_TO_HOST();

    String ACTION_TYPE_FAILED_PINNED_VM_NOT_RUNNING_ON_DEDICATED_HOST();

    String ACTION_TYPE_FAILED_VM_USES_SCSI_RESERVATION();

    String ACTION_TYPE_FAILED_NO_VMS_SPECIFIED();

    String ACTION_TYPE_FAILED_VMS_NOT_FOUND();

    String ACTION_TYPE_FAILED_VMS_NOT_RUNNING_ON_SINGLE_CLUSTER();

    String ACTION_TYPE_FAILED_SGIO_IS_FILTERED();

    String VM_PINNED_TO_HOST_CANNOT_RUN_ON_THE_DEFAULT_VDS();

    String HOST_NAME_NOT_AVAILABLE();

    String MIGRATION_IS_NOT_SUPPORTED();

    String MIGRATION_ON_ERROR_IS_NOT_SUPPORTED();

    String VM_MIGRATION_IS_NOT_SUPPORTED();

    String VM_ID_EXISTS();

    String ACTION_TYPE_FAILED_MIGRATION_OF_NON_MIGRATABLE_PASSTHROUGH_VNICS_IS_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_RUNNING_VM_OR_VM_LEASES_PRESENT_ON_STORAGE_DOMAIN();

    String ACTION_TYPE_FAILED_RETRIEVE_VMS_FOR_WITH_LEASES();

    String ACTION_TYPE_FAILED_VM_LEASES_ARE_NOT_SUPPORTED_WITH_HA_OFF();

    String ACTION_TYPE_FAILED_HOT_SWAPPING_VM_LEASES_NOT_SUPPORTED();

    String VM_PINNING_FORMAT_INVALID();

    String VM_PINNING_VCPU_DOES_NOT_EXIST();

    String VM_PINNING_PCPU_DOES_NOT_EXIST();

    String VM_PINNING_DUPLICATE_DEFINITION();

    String VM_PINNING_PINNED_TO_NO_CPU();

    String ACTION_TYPE_FAILED_VM_CANNOT_BE_HIGHLY_AVAILABLE_AND_PINNED_TO_HOST();

    String ACTION_TYPE_FAILED_VM_CANNOT_BE_HIGHLY_AVAILABLE_AND_HOSTED_ENGINE();

    String ACTION_TYPE_FAILED_VM_CANNOT_BE_HIGH_PERFORMANCE_AND_HOSTED_ENGINE();

    String ACTION_TYPE_FAILED_VM_CANNOT_BE_PINNED_TO_CPU_WITH_UNDEFINED_HOST();

    String ACTION_TYPE_FAILED_VM_MANUAL_PINNING_POLICY_NOT_SELECTED();

    String ACTION_TYPE_FAILED_VM_GUID_ALREADY_EXIST();

    String ACTION_TYPE_FAILED_VM_ATTACHED_TO_POOL();

    String ACTION_TYPE_FAILED_NO_AVAILABLE_POOL_VMS();

    String ACTION_TYPE_FAILED_PRESTARTED_VMS_CANNOT_EXCEED_VMS_COUNT();

    String ACTION_TYPE_FAILED_DISK_VOLUME_TYPE_UNSUPPORTED();

    String ACTION_TYPE_FAILED_NO_SPM();

    String ACTION_TYPE_FAILED_SPM_CHANGED();

    String ACTION_TYPE_FAILED_DISK_SPACE_LOW_ON_STORAGE_DOMAIN();

    String ACTION_TYPE_FAILED_DEDICATED_VDS_NOT_IN_SAME_CLUSTER();

    String ACTION_TYPE_FAILED_DEDICATED_VDS_DOES_NOT_EXIST();

    String ACTION_TYPE_FAILED_DISK_CONFIGURATION_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_OVF_CONFIGURATION_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_MIGRATION_IN_PROGRESS();

    String ACTION_TYPE_FAILED_NOT_SUPPORTED_DISK_STORAGE_TYPE();

    String ACTION_TYPE_FAILED_DISK_LUN_IS_ALREADY_IN_USE();

    String ACTION_TYPE_FAILED_DISK_LUN_HAS_NO_VALID_TYPE();

    String ACTION_TYPE_FAILED_DISK_LUN_ISCSI_MISSING_CONNECTION_PARAMS();

    String ACTION_TYPE_FAILED_DISK_LUN_INVALID();

    String ACTION_TYPE_FAILED_HOSTED_ENGINE_DISK();

    String ACTION_TYPE_FAILED_HOSTED_ENGINE_STORAGE();

    String ACTION_TYPE_FAILED_UNMANAGED_HOSTED_ENGINE();

    String ACTION_TYPE_FAILED_HOSTED_ENGINE_HOST_IN_ANOTHER_DC();

    String ACTION_TYPE_FAILED_HOSTED_ENGINE_HOST_IN_ANOTHER_CLUSTER();

    String ACTION_TYPE_FAILED_MIGRATION_TO_SAME_HOST();

    String ACTION_TYPE_FAILED_DESTINATION_HOST_NOT_IN_DESTINATION_CLUSTER();

    String ACTION_TYPE_FAILED_PROXY_HOST_NOT_IN_VM_DATA_CENTER();

    String ACTION_TYPE_FAILED_INVALID_CUSTOM_PROPERTIES_INVALID_SYNTAX();

    String ACTION_TYPE_FAILED_INVALID_CUSTOM_PROPERTIES_INVALID_KEYS();

    String ACTION_TYPE_FAILED_INVALID_CUSTOM_PROPERTIES_INVALID_VALUES();

    String ACTION_TYPE_FAILED_CUSTOM_PROPERTIES_NOT_SUPPORTED_IN_VERSION();

    String ACTION_TYPE_FAILED_NETWORK_CUSTOM_PROPERTIES_BAD_INPUT();

    String ATTACHMENT_REFERENCE_VLAN_DEVICE();

    String ATTACHMENT_IS_NOT_REUSED();

    String ACTION_TYPE_FAILED_INVALID_DEVICE_TYPE_FOR_CUSTOM_PROPERTIES();

    String ACTION_TYPE_FAILED_VDS_VM_CLUSTER();

    String ACTION_TYPE_FAILED_VDS_VM_MEMORY();

    String ACTION_TYPE_FAILED_VDS_VM_CPUS();

    String ACTION_TYPE_FAILED_VDS_VM_CPU_LEVEL();

    String ACTION_TYPE_FAILED_NO_HA_VDS();

    String CANNOT_MAINTENANCE_VDS_RUN_VMS_NO_OTHER_RUNNING_VDS();

    String ACTION_TYPE_FAILED_VDS_VM_VERSION();

    String ACTION_TYPE_FAILED_VDS_VM_SWAP();

    String ACTION_TYPE_FAILED_NO_VDS_AVAILABLE_IN_CLUSTER();

    String ACTION_TYPE_FAILED_CANNOT_REMOVE_IMAGE_TEMPLATE();

    String ACTION_TYPE_FAILED_PROBLEM_WITH_CANDIDATE_INFO();

    String ACTION_TYPE_FAILED_TEMPLATE_DOES_NOT_EXIST();

    String ACTION_TYPE_FAILED_TEMPLATE_IS_ON_DIFFERENT_CHAIN();

    String ACTION_TYPE_FAILED_CLUSTER_CAN_NOT_BE_EMPTY();

    String ACTION_TYPE_FAILED_TEMPLATE_VERSION_CANNOT_BE_BASE_TEMPLATE();

    String ACTION_TYPE_FAILED_TEMPLATE_CANNOT_BE_CREATED_WITH_EMPTY_DISK_ALIAS();

    String ACTION_TYPE_FAILED_INSTANCE_TYPE_DOES_NOT_EXIST();

    String ACTION_TYPE_FAILED_IMAGE_TYPE_DOES_NOT_EXIST();

    String ACTION_TYPE_FAILED_TEMPLATE_IS_DISABLED();

    String ACTION_TYPE_FAILED_TEMPLATE_NOT_EXISTS_IN_CURRENT_DC();

    String ACTION_TYPE_FAILED_IMAGE_ALREADY_EXISTS();

    String ACTION_TYPE_FAILED_TEMPLATE_GUID_ALREADY_EXISTS();

    String ACTION_TYPE_FAILED_TEMPLATE_ID_CANT_BE_CHANGED();

    String ACTION_TYPE_FAILED_TEMPLATE_IS_BEING_SET_AS_BASE_TEMPLATE();

    String ACTION_TYPE_FAILED_SUBVERSION_BEING_CONCURRENTLY_REMOVED();

    String CLUSTER_UPGRADE_NOT_FINISHED();

    String CLUSTER_UPGRADE_CAN_NOT_BE_STARTED();

    String MIXED_HOST_VERSIONS_NOT_ALLOWED();

    String VM_CANNOT_SUSPEND_CLUSTER_UPGRADING();

    String BOUND_TO_HOST_WHILE_UPGRADING_CLUSTER();

    String CLUSTER_UPGRADE_DETAIL_HOST_INVALID_OS();

    String CLUSTER_UPGRADE_DETAIL_HOST_RUNS_TOO_OLD_OS();

    String CLUSTER_UPGRADE_DETAIL_VM_NOT_MIGRATABLE();

    String CLUSTER_UPGRADE_DETAIL_VM_CPUS_PINNED();

    String CLUSTER_UPGRADE_DETAIL_VM_NUMA_PINNED();

    String CLUSTER_UPGRADE_DETAIL_VM_NEEDS_PASSTHROUGH();

    String CLUSTER_UPGRADE_DETAIL_VM_SUSPENDED();

    String CLUSTER_VERSION_CHANGE_VM_PREVIEW();

    String ACTION_TYPE_FAILED_ROLE_IS_READ_ONLY();

    String ACTION_TYPE_FAILED_STORAGE_POOL_NOT_MATCH();

    String ACTION_TYPE_FAILED_STORAGE_POOL_OF_VM_NOT_MATCH();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_ALREADY_CONTAINS_DISK();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_NOT_SPECIFIED();

    String ACTION_TYPE_FAILED_STORAGE_DELETE_PROTECTED();

    String ACTION_TYPE_FAILED_STORAGE_VMS_IN_POOL();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_NAME_ALREADY_EXIST();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_ALREADY_EXIST();

    String ACTION_TYPE_FAILED_IMPORT_STORAGE_DOMAIN_EXTERNAL_LUN_DISK_EXIST();

    String ACTION_TYPE_FAILED_STORAGE_POOL_NAME_ALREADY_EXIST();

    String ACTION_TYPE_FAILED_DESTINATION_STORAGE_DOMAIN_ALREADY_CONTAINS_THE_DISK();

    String ACTION_TYPE_FAILED_SOURCE_STORAGE_DOMAIN_DOES_CONTAINS_THE_DISK();

    String ACTION_TYPE_FAILED_TEMPLATE_NOT_FOUND_ON_DESTINATION_DOMAIN();

    String ACTION_TYPE_FAILED_TEMPLATE_DISK_STATUS_IS_NOT_VALID();

    String ACTION_TYPE_FAILED_INVALID_POOL_NAME();

    String ACTION_TYPE_FAILED_NO_VDS_IN_POOL();

    String VAR__TYPE__HOST();

    String VAR__ENTITIES__HOSTS();

    String VAR__ENTITIES__HOST();

    String VAR__TYPE__NETWORKS();

    String VAR__TYPE__NETWORK();

    String VAR__TYPE__LABEL();

    String VAR__TYPE__HOST_NIC_VFS_CONFIG();

    String VAR__TYPE__HOST_NIC_VFS_CONFIG_NETWORK();

    String VAR__TYPE__HOST_NIC_VFS_CONFIG_LABEL();

    String VAR__TYPE__VNIC_PROFILE();

    String VAR__TYPE__PROVIDER();

    String VAR__TYPE__PROVIDER_CERTIFICATE();

    String VAR__TYPE__VM();

    String VAR__ENTITIES__VMS();

    String VAR__ENTITIES__VM();

    String VAR__ENTITIES__GLUSTER_BRICKS();

    String VAR__ENTITIES__GLUSTER_BRICK();

    String VAR__TYPE__QUOTA();

    String VAR__TYPE__COMPUTER_ACCOUNT();

    String VAR__TYPE__VM_BACKUP();

    String VAR__TYPE__CHECKPOINT();

    String VAR__TYPE__VM_TEMPLATE();

    String VAR__ENTITIES__VM_TEMPLATES();

    String VAR__ENTITIES__VM_TEMPLATE();

    String VAR__ENTITIES__DISKS();

    String VAR__TYPE__SNAPSHOT();

    String VAR__TYPE__DESKTOP_POOL();

    String VAR__TYPE__VM_FROM_VM_POOL();

    String VAR__TYPE__CLUSTER();

    String VAR__TYPE__ROLE();

    String VAR__TYPE__INTERFACE();

    String VAR__TYPE__DISK();

    String VAR__TYPE__LUNS();

    String VAR__TYPE__BOOKMARK();

    String VAR__TYPE__VM_TICKET();

    String VAR__TYPE__STORAGE__CONNECTION();

    String VAR__TYPE__STORAGE__CONNECTION__EXTENSION();

    String VAR__TYPE__STORAGE__DOMAIN();

    String VAR__TYPE__STORAGE__POOL();

    String VAR__TYPE__MAC__POOL();

    String VAR__TYPE__USER_FROM_VM();

    String VAR__TYPE__USER();

    String VAR__TYPE__PERMISSION();

    String VAR__TYPE__HOST_CAPABILITIES();

    String VAR__TYPE__NETWORK_QOS();

    String VAR__TYPE__QOS();

    String VAR__TYPE__SPM();

    String VAR__TYPE__CLUSTER_POLICY();

    String VAR__TYPE__POLICY_UNIT();

    String VAR__TYPE__SUBNET();

    String VAR__TYPE__AFFINITY_GROUP();

    String VAR__TYPE__ISCSI_BOND();

    String VAR__TYPE__DISK__SNAPSHOT();

    String VAR__TYPE__DISK_PROFILE();

    String VAR__TYPE__CPU_PROFILE();

    String VAR__TYPE__AUTHENTICATION_KEY();

    String VAR__TYPE__GLUSTER_VOLUME_SNAPSHOT();

    String VAR__TYPE__GLUSTER_VOLUME_SNAPSHOT_CONFIG();

    String VAR__TYPE__GLUSTER_GEOREP_SESSION();

    String VAR__TYPE__HOST_DEVICES();

    String VAR__TYPE__USER_PROFILE_PROPERTY();

    String VAR__TYPE__MEMORY_DEVICE();

    String VAR_TYPE_FENCE_AGENT();

    String VAR__ACTION__RUN();

    String VAR__ACTION__REMOVE();

    String VAR__ACTION__ADD();

    String VAR__ACTION__CREATE();

    String VAR__ACTION__RESTORE();

    String VAR__ACTION__PAUSE();

    String VAR__ACTION__HIBERNATE();

    String VAR__ACTION__MIGRATE();

    String VAR__ACTION__CANCEL_MIGRATE();

    String VAR__ACTION__CANCEL_CONVERSION();

    String VAR__ACTION__ATTACH_DESKTOP_TO();

    String VAR__ACTION__REVERT_TO();

    String VAR__ACTION__PREVIEW();

    String VAR__ACTION__STOP();

    String VAR__ACTION__START();

    String VAR__ACTION__RESTART();

    String VAR__ACTION__FREEZE();

    String VAR__ACTION__THAW();

    String VAR__ACTION__SPARSIFY();

    String VAR__ACTION__AMEND();

    String VAR__ACTION__SHUTDOWN();

    String VAR__ACTION__EXPORT();

    String VAR__ACTION__EXTEND();

    String VAR__ACTION__IMPORT();

    String VAR__ACTION__ATTACH_ACTION_TO();

    String VAR__ACTION__DETACH_ACTION_TO();

    String VAR__ACTION__MOVE();

    String VAR__ACTION__COPY();

    String VAR__ACTION__CHANGE_CD();

    String VAR__ACTION__EJECT_CD();

    String VAR__ACTION__ALLOCATE_AND_RUN();

    String VAR__ACTION__MANUAL_FENCE();

    String VAR__ACTION__MAINTENANCE();

    String VAR__ACTION__SETUP();

    String VAR__ACTION__SET();

    String VAR__ACTION__RESET();

    String VAR__ACTION__UPDATE();

    String VAR__ACTION__ATTACH();

    String VAR__ACTION__DETACH();

    String VAR__ACTION__ACTIVATE();

    String VAR__ACTION__DEACTIVATE();

    String VAR__ACTION__SCAN();

    String VAR__ACTION__RECONSTRUCT_MASTER();

    String VAR__ACTION__UPDATE_OVFS();

    String VAR__ACTION__RECOVER_POOL();

    String VAR__ACTION__DESTROY_DOMAIN();

    String VAR__ACTION__HOT_PLUG();

    String VAR__ACTION__HOT_UNPLUG();

    String VAR__ACTION__HOT_SET_CPUS();

    String VAR__ACTION__HOT_SET_MEMORY();

    String VAR__ACTION__LOGON();

    String VAR__ACTION__LOGOFF();

    String VAR__ACTION__REBALANCE_START();

    String VAR__ACTION__REMOVE_BRICKS_START();

    String VAR__ACTION__REBALANCE_STOP();

    String VAR__ACTION__REMOVE_BRICKS_STOP();

    String VAR__ACTION__REMOVE_BRICKS_COMMIT();

    String VAR__ACTION__SYNC();

    String VAR__ACTION__REGISTER();

    String VAR__ACTION__UPGRADE();

    String VAR__ACTION__INSTALL();

    String VAR__ACTION__ENROLL_CERTIFICATE();

    String VAR__ACTION__START_PROFILE();

    String VAR__ACTION__STOP_PROFILE();

    String VAR__ACTION__FORCE_SELECT();

    String VAR__ACTION__SWITCH_MASTER();

    String VAR__ACTION__ASSIGN();

    String VAR__ACTION__REFRESH();

    String VAR__ACTION__ENABLE();

    String VAR__ACTION__DISABLE();

    String VAR__ACTION__UPDATE_VM_VERSION();

    String VAR__ACTION__VOLUME_SNAPSHOT_CONFIG_UPDATE();

    String VAR__ACTION__SCHEDULE();

    String VAR__ACTION__TRANSFER();

    String VAR__ACTION__BACKUP();

    String VAR__ACTION__COPY_NETWORKS();

    String VAR__ACTION__SCREENSHOT();

    String VAR__HOST_STATUS__UP();

    String VAR__HOST_STATUS__UP_MAINTENANCE_OR_NON_OPERATIONAL();

    String VAR__VM_STATUS__UP();

    String VAR__VM_STATUS__UNASSIGNED();

    String VAR__VM_STATUS__DOWN();

    String VAR__VM_STATUS__POWERING_UP();

    String VAR__VM_STATUS__PAUSED();

    String VAR__VM_STATUS__MIGRATING();

    String VAR__VM_STATUS__UNKNOWN();

    String VAR__VM_STATUS__NOT_RESPONDING();

    String VAR__VM_STATUS__WAIT_FOR_LAUNCH();

    String VAR__VM_STATUS__REBOOT_IN_PROGRESS();

    String VAR__VM_STATUS__SAVING_STATE();

    String VAR__VM_STATUS__RESTORING_STATE();

    String VAR__VM_STATUS__SUSPENDED();

    String VAR__VM_STATUS__IMAGE_LOCKED();

    String VAR__VM_STATUS__POWERING_DOWN();

    String VAR__VM_STATUS__IMAGE_ILLEGAL();

    String VAR__TYPE__GLUSTER_VOLUME();

    String VAR__TYPE__GLUSTER_VOLUME_OPTION();

    String VAR__TYPE__GLUSTER_BRICK();

    String VAR__TYPE__GLUSTER_SERVER();

    String VAR__TYPE__GLUSTER_HOOK();

    String VAR__TYPE__GLUSTER_SERVICE();

    String VAR__TYPE__GLUSTER_WEBHOOK();

    String VAR__TYPE__STORAGE_DEVICE();

    String VAR__TYPE__STORAGE_DOMAIN_DR();

    String ACTION_TYPE_FAILED_DISK_ALREADY_ATTACHED();

    String ACTION_TYPE_FAILED_ILLEGAL_DISK_OPERATION();

    String ACTION_TYPE_FAILED_ILLEGAL_ARCHITECTURE_TYPE_INCOMPATIBLE();

    String ACTION_TYPE_FAILED_DISK_ALREADY_DETACHED();

    String ACTION_TYPE_FAILED_NOT_SHAREABLE_DISK_ALREADY_ATTACHED();

    String ACTION_TYPE_FAILED_MISSED_STORAGES_FOR_SOME_DISKS();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_IS_WRONG();

    String ACTION_TYPE_FAILED_CANT_DELETE_TEMPLATE_DISK_WITHOUT_SPECIFYING_DOMAIN();

    String ACTION_TYPE_FAILED_CPU_NOT_FOUND();

    String ACTION_TYPE_FAILED_EXCEEDED_MAX_PCI_SLOTS();

    String ACTION_TYPE_FAILED_EXCEEDED_MAX_IDE_SLOTS();

    String ACTION_TYPE_FAILED_EXCEEDED_MAX_SATA_SLOTS();

    String ACTION_TYPE_FAILED_EXCEEDED_MAX_VIRTIO_SCSI_DISKS();

    String ACTION_TYPE_FAILED_EXCEEDED_MAX_SPAPR_VSCSI_DISKS();

    String USER_FAILED_TO_AUTHENTICATE();

    String USER_FAILED_TO_AUTHENTICATE_SERVER_IS_NOT_AVAILABLE();

    String USER_FAILED_TO_AUTHENTICATE_TIMED_OUT();

    String USER_FAILED_TO_AUTHENTICATE_KERBEROS_ERROR();

    String USER_FAILED_TO_AUTHENTICATION_WRONG_AUTHENTICATION_METHOD();

    String VMT_CLUSTER_IS_NOT_VALID();

    String USER_ACCOUNT_DISABLED();

    String USER_ACCOUNT_EXPIRED();

    String USER_PERMISSION_DENIED();

    String USER_CANNOT_LOGIN_SESSION_MISSING();

    String USER_CANNOT_REMOVE_ADMIN_USER();

    String USER_MUST_EXIST_IN_DB();

    String USER_MUST_EXIST_IN_DIRECTORY();

    String USER_IS_ALREADY_LOGGED_IN();

    String USER_IS_NOT_LOGGED_IN();

    String USER_DOES_NOT_HAVE_A_VALID_EMAIL();

    String VM_POOL_CANNOT_CREATE_FROM_BLANK_TEMPLATE();

    String VM_POOL_CANNOT_UPDATE_POOL_NOT_FOUND();

    String VM_CANNOT_SUSPENDE_HAS_RUNNING_TASKS();

    String VM_CANNOT_SUSPEND_STATELESS_VM();

    String VM_CANNOT_SUSPEND_VM_FROM_POOL();

    String VM_AT_LEAST_ONE_SPECIFIED();

    String USER_NOT_AUTHORIZED_TO_PERFORM_ACTION();

    String NON_ADMIN_USER_NOT_AUTHORIZED_TO_PERFORM_ACTION_ON_HE();

    String ERROR_CANNOT_REMOVE_ROLE_ATTACHED_TO_PERMISSION();

    String ERROR_CANNOT_REMOVE_ROLE_INVALID_ROLE_ID();

    String ERROR_CANNOT_UPDATE_ROLE_ID();

    String ERROR_CANNOT_UPDATE_ROLE_TYPE();

    String VDS_APPROVE_VDS_IN_WRONG_STATUS();

    String VDS_CLUSTER_IS_NOT_VALID();

    String CLUSTER_CANNOT_UPDATE_CPU_ILLEGAL();

    String CLUSTER_CANNOT_UPDATE_CPU_ARCHITECTURE_ILLEGAL();

    String CLUSTER_CANNOT_UPDATE_CPU_WITH_HOSTS_MISSING_FLAGS();

    String CLUSTER_CANNOT_UPDATE_COMPATIBILITY_VERSION_WITH_LOWER_HOSTS();

    String CLUSTER_CANNOT_UPDATE_COMPATIBILITY_VERSION_WITH_INCOMPATIBLE_EMULATED_MACHINE();

    String CLUSTER_CANNOT_UPDATE_SUPPORTED_FEATURES_WITH_LOWER_HOSTS();

    String CLUSTER_CANNOT_UPDATE_VERSION_WHEN_NO_HOST_SUPPORTS_THE_VERSION();

    String CLUSTER_CANNOT_SET_CPU_AUTODETECTION();

    String CLUSTER_CANNOT_UPDATE_VDS_UP();

    String CLUSTER_CANNOT_UPDATE_FIPS_VDS_MAINTENANCE();

    String CLUSTER_CANNOT_ADD_COMPATIBILITY_VERSION_WITH_LOWER_STORAGE_POOL();

    String CLUSTER_CANNOT_DO_ACTION_NAME_IN_USE();

    String CLUSTER_CANNOT_SET_TRUSTED_ATTESTATION_SERVER_NOT_CONFIGURED();

    String CLUSTER_HOSTS_MUST_BE_DOWN();

    String CLUSTER_TO_ALLOW_MEMORY_OPTIMIZATION_YOU_MUST_ALLOW_KSM_OR_BALLOONING();

    String CLUSTER_IMPLICIT_AFFINITY_GROUP_IS_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_NAME_ALREADY_USED();

    String ACTION_TYPE_FAILED_STORAGE_CONNECTION_NOT_EXIST();

    String ACTION_TYPE_FAILED_UNSUPPORTED_ACTION_FOR_MANAGED_BLOCK_STORAGE_TYPE();

    String ACTION_TYPE_FAILED_STORAGE_CONNECTION_FOR_DOMAIN_NOT_EXIST();

    String ACTION_TYPE_FAILED_NO_SUITABLE_DOMAIN_FOUND();

    String ACTION_TYPE_FAILED_ACTION_IS_SUPPORTED_ONLY_FOR_ISCSI_DOMAINS();

    String ACTION_TYPE_FAILED_ACTION_IS_SUPPORTED_ONLY_FOR_DATA_DOMAINS();

    String ACTION_TYPE_FAILED_STORAGE_CONNECTION_ID_EMPTY();

    String ACTION_TYPE_FAILED_STORAGE_CONNECTION_ALREADY_EXISTS();

    String ACTION_TYPE_FAILED_STORAGE_CONNECTION_FOR_DOMAIN_ALREADY_EXISTS();

    String ACTION_TYPE_FAILED_STORAGE_CONNECTION_UNSUPPORTED_ACTION_FOR_STORAGE_TYPE();

    String ACTION_TYPE_FAILED_UNSUPPORTED_ACTION_DOMAIN_MUST_BE_IN_MAINTENANCE_OR_UNATTACHED();

    String ACTION_TYPE_FAILED_STORAGE_CONNECTION_UNSUPPORTED_ACTION_NOT_SAME_STORAGE_TYPE();

    String ACTION_TYPE_FAILED_STORAGE_CONNECTION_UNSUPPORTED_ACTION_FOR_RUNNING_VMS();

    String ACTION_TYPE_FAILED_STORAGE_CONNECTION_UNSUPPORTED_ACTION_FOR_RUNNING_VMS_AND_DOMAINS_STATUS();

    String ACTION_TYPE_FAILED_STORAGE_CONNECTION_BELONGS_TO_SEVERAL_STORAGE_DOMAINS();

    String ACTION_TYPE_FAILED_STORAGE_CONNECTION_BELONGS_TO_SEVERAL_STORAGE_DOMAINS_AND_DISKS();

    String ACTION_TYPE_FAILED_STORAGE_CONNECTION_BELONGS_TO_SEVERAL_DISKS();

    String ACTION_TYPE_FAILED_STORAGE_CONNECTION_EXTENSION_ALREADY_EXISTS();

    String ACTION_TYPE_FAILED_STORAGE_CONNECTION_EXTENSION_DOES_NOT_EXIST();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_NOT_EXIST();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_AND_CLUSTER_IN_DIFFERENT_POOL();

    String ACTION_TYPE_FAILED_VDS_NOT_IN_DEST_STORAGE_POOL();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_STATUS_ILLEGAL();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_STATUS_ILLEGAL2();

    String STORAGE_POOL_REINITIALIZE_WITH_MORE_THAN_ONE_DATA_DOMAIN();

    String ACTION_TYPE_FAILED_STORAGE_POOL_NOT_EXIST();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_NOT_IN_STORAGE_POOL();

    String ACTION_TYPE_FAILED_LUNS_ALREADY_PART_OF_STORAGE_DOMAINS();

    String ACTION_TYPE_FAILED_LUNS_ALREADY_USED_BY_DISKS();

    String ACTION_TYPE_FAILED_CANNOT_SYNC_LUNS_OF_NON_BLOCK_DOMAINS();

    String ACTION_TYPE_FAILED_LUN_BREAKS_STORAGE_DOMAIN_PASS_DISCARD_SUPPORT();

    String ACTION_TYPE_FAILED_LUN_BREAKS_STORAGE_DOMAIN_DISCARD_AFTER_DELETE();

    String ACTION_TYPE_FAILED_DUPLICATE_DEVICE();

    String ACTION_TYPE_FAILED_CANNOT_REMOVE_ALL_LUNS();

    String ACTION_TYPE_FAILED_DEVICE_NOT_IN_STORAGE_DOMAIN();

    String ACTION_TYPE_FAILED_OPERATION_ON_METADATA_DEVICES();

    String ACTION_TYPE_FAILED_NO_DEVICES_PROVIDED();

    String ERROR_CANNOT_REMOVE_STORAGE_POOL_WITH_NONMASTER_DOMAINS();

    String ERROR_CANNOT_MANAGE_STORAGE_DOMAIN();

    String ERROR_CANNOT_FORCE_REMOVE_STORAGE_POOL_WITH_VDS_NOT_IN_MAINTENANCE();

    String ACTION_TYPE_FAILED_STORAGE_POOL_STATUS_ILLEGAL();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_BELONGS_TO_DIFFERENT_STORAGE_POOL();

    String NETWORK_BOND_NOT_EXISTS();

    String NETWORK_INTERFACE_ALREADY_IN_BOND();

    String ACTION_TYPE_FAILED_NETWORK_ATTACHMENTS_REFERENCES_SAME_NETWORK_DUPLICATELY();

    String NETWORK_ATTACHMENT_IN_BOTH_LISTS();

    String NIC_NOT_EXISTS_ON_HOST();

    String NETWORK_INTERFACE_ADDED_TO_BOND_AND_NETWORK_IS_ATTACHED_TO_IT_AT_THE_SAME_TIME();

    String NETWORK_INTERFACE_ATTACHED_TO_NETWORK_CANNOT_BE_SLAVE();

    String NETWORK_INTERFACE_BOND_OR_VLAN_CANNOT_BE_SLAVE();

    String NETWORK_NAME_USED_AS_VDSM_NETWORK_NAME();

    String NETWORK_INTERFACE_REFERENCED_AS_A_SLAVE_MULTIPLE_TIMES();

    String CANNOT_ADD_NETWORK_ATTACHMENT_ON_SLAVE_OR_VLAN();

    String NETWORK_ATTACHMENT_NOT_SPECIFIED();

    String NETWORK_ATTACHMENT_WHEN_UPDATING_YOU_HAVE_TO_PROVIDE_ID();

    String NETWORK_ATTACHMENT_CANNOT_BE_CREATED_WITH_SPECIFIC_ID();

    String BOND_USED_BY_NETWORK_ATTACHMENTS();

    String NULL_PASSED_AS_NETWORK_ATTACHMENT();

    String MODIFIED_NETWORK_ATTACHMENT_DOES_NOT_EXISTS();

    String NETWORK_ATTACHMENT_NETWORK_ID_OR_NAME_IS_NOT_SET();

    String NETWORK_ATTACHMENTS_TO_BE_REMOVED_DOES_NOT_EXISTS();

    String NETWORK_ATTACHMENT_REFERENCES_NICS_INCOHERENTLY();

    String NIC_LABEL_REFERENCES_NICS_INCOHERENTLY();

    String BOND_REFERENCES_NICS_INCOHERENTLY();

    String NETWORK_ATTACHMENT_REFERENCES_NETWORK_INCOHERENTLY();

    String NETWORK_ALREADY_ATTACHED_TO_HOST();

    String CANNOT_CHANGE_ATTACHED_NETWORK();

    String ACTION_TYPE_FAILED_ROLE_NETWORK_HAS_NO_BOOT_PROTOCOL();

    String INTERFACE_ON_NIC_LABEL_NOT_EXIST();

    String LABEL_NOT_EXIST_IN_HOST();

    String PARAMS_CONTAIN_DUPLICATE_LABELS();

    String LABEL_ATTACH_TO_IMPROPER_INTERFACE();

    String ERROR_CANNOT_ATTACH_MORE_THAN_ONE_ISO_DOMAIN();

    String ERROR_CANNOT_ATTACH_MORE_THAN_ONE_EXPORT_DOMAIN();

    String ERROR_CANNOT_ATTACH_STORAGE_DOMAIN_STORAGE_TYPE_NOT_MATCH();

    String ERROR_CANNOT_CHANGE_STORAGE_POOL_TYPE_WITH_LOCAL();

    String NETWORK_NOT_EXISTS();

    String NETWORK_HAVING_ID_NOT_EXISTS();

    String NETWORK_HAVING_NAME_NOT_EXISTS();

    String NETWORK_IS_NOT_EXTERNAL();

    String ACTION_TYPE_FAILED_NETWORK_QOS_NOT_EXISTS();

    String ACTION_TYPE_FAILED_NETWORK_ATTACHMENT_CONTAINS_DUPLICATES();

    String ACTION_TYPE_FAILED_VNIC_PROFILE_NOT_EXISTS();

    String ACTION_TYPE_FAILED_VNIC_PROFILE_NAME_IN_USE();

    String ACTION_TYPE_FAILED_VNIC_PROFILE_IN_ONE_USE();

    String ACTION_TYPE_FAILED_VNIC_PROFILE_IN_MANY_USES();

    String ACTION_TYPE_FAILED_CANNOT_CHANGE_VNIC_PROFILE_NETWORK();

    String ACTION_TYPE_FAILED_CANNOT_ADD_VNIC_PROFILE_TO_NON_VM_NETWORK();

    String ACTION_TYPE_FAILED_PASSTHROUGH_PROFILE_NOT_SUPPORTS_PORT_ISOLATION();

    String ACTION_TYPE_FAILED_CANNOT_FIND_VNIC_PROFILE_FOR_NETWORK();

    String EXTERNAL_NETWORK_HAVING_NAME_CANNOT_BE_PROVISIONED();

    String NETWORK_LABEL_FORMAT_INVALID();

    String ACTION_TYPE_FAILED_NETWORK_ALREADY_LABELED();

    String ACTION_TYPE_FAILED_CANNOT_REMOVE_LABELED_NETWORK_FROM_NIC();

    String ACTION_TYPE_FAILED_CANNOT_MOVE_LABELED_NETWORK_TO_ANOTHER_NIC();

    String NETWORK_SHOULD_BE_ATTACHED_VIA_LABEL_TO_ANOTHER_NIC();

    String ACTION_TYPE_FAILED_CANNOT_REMOVE_NETWORK_FROM_BRICK();

    String LABELED_NETWORK_ATTACHED_TO_WRONG_INTERFACE();

    String OTHER_INTERFACE_ALREADY_LABELED();

    String ACTION_TYPE_FAILED_NUM_OF_VFS_CANNOT_BE_CHANGED();

    String ACTION_TYPE_FAILED_NIC_IS_NOT_SRIOV_ENABLED();

    String ACTION_TYPE_FAILED_NUM_OF_VFS_NOT_IN_VALID_RANGE();

    String ACTION_TYPE_FAILED_CANNOT_SET_SPECIFIC_NETWORKS();

    String ACTION_TYPE_FAILED_NETWORK_ALREADY_IN_VFS_CONFIG();

    String ACTION_TYPE_FAILED_NETWORK_NOT_IN_VFS_CONFIG();

    String ACTION_TYPE_FAILED_PORT_ISOLATION_UNSUPPORTED_CLUSTER_LEVEL();

    String ACTION_TYPE_FAILED_PORT_ISOLATION_INCOMPATIBLE_SWITCH_TYPE();

    String ACTION_TYPE_FAILED_NETWORK_NOT_EXIST();

    String ACTION_TYPE_FAILED_LABEL_ALREADY_IN_VFS_CONFIG();

    String ACTION_TYPE_FAILED_LABEL_NOT_IN_VFS_CONFIG();

    String ERROR_CANNOT_DETACH_LAST_STORAGE_DOMAIN();

    String ERROR_CANNOT_DESTROY_LAST_STORAGE_DOMAIN();

    String ERROR_CANNOT_DESTROY_LAST_STORAGE_DOMAIN_HOST_NOT_ACTIVE();

    String NETWORK_VLAN_OUT_OF_RANGE();

    String ERROR_CANNOT_ADD_STORAGE_POOL_WITHOUT_DATA_DOMAIN();

    String ERROR_CANNOT_ADD_STORAGE_DOMAIN_WITH_ATTACHED_DATA_DOMAIN();

    String ERROR_CANNOT_REMOVE_POOL_WITH_ACTIVE_DOMAINS();

    String STORAGE_DOMAIN_DOES_NOT_EXIST();

    String CANNOT_FETCH_STORAGE_DEVICES_HOST_DOESNT_EXIST_ANYMORE();

    String NIC_ID_IS_NULL();

    String NIC_ID_NOT_EXIST();

    String INTERFACE_TYPE_NOT_SUPPORT_LLDP();

    String CLUSTER_CANNOT_CHANGE_STORAGE_POOL();

    String ACTION_TYPE_FAILED_SETUP_NETWORKS_OR_REFRESH_IN_PROGRESS();

    String ACTION_TYPE_FAILED_NETWORK_NAME_IN_USE();

    String ACTION_TYPE_FAILED_NETWORK_IN_ONE_USE();

    String ACTION_TYPE_FAILED_NETWORK_IN_MANY_USES();

    String ERROR_CANNOT_CREATE_STORAGE_DOMAIN_WITHOUT_VG_LV();

    String NETWORK_INTERFACE_TEMPLATE_CANNOT_BE_SET();

    String NETWORK_INTERFACE_VM_CANNOT_BE_SET();

    String EN_UNKNOWN_NOTIFICATION_METHOD();

    String EN_UNSUPPORTED_NOTIFICATION_EVENT();

    String EN_ALREADY_SUBSCRIBED();

    String EN_NOT_SUBSCRIBED();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_TYPE_ILLEGAL();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_VERSION_UNSUPPORTED();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_IS_BEING_REDUCED();

    String ACTION_TYPE_FAILED_DOMAIN_TYPE_CAN_BE_CREATED_ONLY_ON_SPECIFIC_STORAGE_DOMAINS();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_FORMAT_ILLEGAL();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_FORMAT_ILLEGAL_HOST();

    String ACTION_TYPE_FAILED_FORMAT_STORAGE_DOMAIN_WITH_ATTACHED_DATA_DOMAIN();

    String ACTION_TYPE_FAILED_CANNOT_FORMAT_MANAGED_BLOCK_STORAGE_DOMAIN();

    String ERROR_CANNOT_EXTEND_CONNECTION_FAILED();

    String ERROR_CANNOT_CHANGE_STORAGE_DOMAIN_FIELDS();

    String ERROR_CANNOT_UPDATE_STORAGE_POOL_COMPATIBILITY_VERSION_BIGGER_THAN_CLUSTERS();

    String ERROR_CANNOT_UPDATE_STORAGE_POOL_SUSPENDED_VM_COMPATIBILITY_VERSION_NOT_SUPPORTED();

    String ERROR_CANNOT_ADD_EXISTING_STORAGE_DOMAIN_CONNECTION_DATA_ILLEGAL();

    String NETWORK_MAC_ADDRESS_IN_USE();

    String NETWORK_MAC_ADDRESS_IN_USE_DETAILED();

    String ERROR_GET_STORAGE_DOMAIN_LIST();

    String NETWORK_INTERFACE_IN_USE_BY_VM();

    String NETWORK_CLUSTER_NETWORK_IN_USE();

    String ERROR_CANNOT_DEACTIVATE_MASTER_WITH_NON_DATA_DOMAINS();

    String ERROR_CANNOT_DEACTIVATE_DOMAIN_WITH_TASKS();

    String ERROR_CANNOT_DEACTIVATE_MASTER_DOMAIN_WITH_TASKS_ON_POOL();

    String ERROR_CANNOT_DEACTIVATE_DOMAIN_WITH_RUNNING_VMS_WITH_LEASES();

    String ERROR_CANNOT_REMOVE_LAST_SUPER_USER_ROLE();

    String VM_CANNOT_REMOVE_VM_WHEN_STATUS_IS_NOT_DOWN();

    String VM_CANNOT_REMOVE_WITH_DETACH_DISKS_SNAPSHOTS_EXIST();

    String VM_CANNOT_REMOVE_WITH_DETACH_DISKS_BASED_ON_TEMPLATE();

    String ACTION_TYPE_FAILED_MASTER_STORAGE_DOMAIN_NOT_ACTIVE();

    String TAGS_SPECIFY_TAG_IS_NOT_EXISTS();

    String NETWORK_CANNOT_ADD_INTERFACE_WHEN_VM_STATUS_NOT_UP_DOWN_LOCKED();

    String NETWORK_VLAN_IN_USE();

    String NETWORK_CLUSTER_HAVE_NOT_EXISTING_DATA_CENTER_NETWORK();

    String NETWORK_NOT_EXISTS_IN_CURRENT_CLUSTER();

    String NETWORK_NOT_IN_SYNC();

    String MTU();

    String BRIDGED();

    String VLAN();

    String IPV4_BOOT_PROTOCOL();

    String IPV4_ADDRESS();

    String IPV4_NETMASK();

    String IPV4_GATEWAY();

    String IPV6_BOOT_PROTOCOL();

    String IPV6_ADDRESS();

    String IPV6_PREFIX();

    String IPV6_GATEWAY();

    String OUT_AVERAGE_LINK_SHARE();

    String OUT_AVERAGE_UPPER_LIMIT();

    String OUT_AVERAGE_REAL_TIME();

    String SWITCH_TYPE();

    String DNS_CONFIGURATION();

    String DEFAULT_ROUTE();

    String HOST_OUT_OF_SYNC();

    String DC_OUT_OF_SYNC();

    String NETWORK_INTERFACES_ALREADY_SPECIFIED();

    String ACTION_TYPE_FAILED_EXTERNAL_NETWORKS_CANNOT_BE_PROVISIONED();

    String NETWORKS_ALREADY_ATTACHED_TO_IFACES();

    String NETWORK_INTERFACES_DONT_EXIST();

    String NETWORKS_DONT_EXIST_IN_CLUSTER();

    String NETWORKS_DONT_EXIST_IN_DATA_CENTER();

    String NETWORK_INTERFACES_NOT_EXCLUSIVELY_USED_BY_UNTAGGED_NETWORK();

    String NETWORK_BONDS_INVALID_SLAVE_COUNT();

    String NETWORK_CANNOT_DETACH_NETWORK_USED_BY_VMS();

    String NON_VM_NETWORK_CANNOT_SUPPORT_STP();

    String NON_VM_NETWORK_CANNOT_SUPPORT_PORT_ISOLATION();

    String EXTERNAL_NETWORK_CANNOT_SUPPORT_PORT_ISOLATION();

    String NETWORK_MTU_DIFFERENCES();

    String ACTION_TYPE_FAILED_NETWORK_FROM_DIFFERENT_DC();

    String ACTION_TYPE_FAILED_DEFAULT_MANAGEMENT_NETWORK_NOT_FOUND();

    String ACTION_TYPE_FAILED_MANAGEMENT_NETWORK_CANNOT_BE_CHANGED();

    String ACTION_TYPE_FAILED_TARGET_CLUSTER_WITH_DIFF_MANAGEMENT_NETWORK();

    String ACTION_TYPE_FAILED_MANAGEMENT_NETWORK_CANNOT_BE_EXTERNAL();

    String ACTION_TYPE_FAILED_DUPLICATE_NETWORK_CLUSTER_INPUT();

    String ACTION_TYPE_FAILED_PROVIDER_DOESNT_EXIST();

    String ACTION_TYPE_FAILED_CANNOT_CHANGE_PROVIDER_TYPE();

    String ACTION_TYPE_FAILED_PROVIDER_NOT_NETWORK();

    String ACTION_TYPE_FAILED_HOST_PROVIDER_TYPE_MISMATCH();

    String ACTION_TYPE_FAILED_PROVIDER_NETWORKS_USED_MULTIPLE_TIMES();

    String ACTION_TYPE_FAILED_PROVIDER_NETWORKS_USED_ONCE();

    String ACTION_TYPE_FAILED_PROVIDER_USED_IN_CLUSTER();

    String ACTION_TYPE_FAILED_EXTERNAL_NETWORK_ALREADY_EXISTS();

    String ACTION_TYPE_FAILED_EXTERNAL_NETWORK_MUST_BE_VM_NETWORK();

    String ACTION_TYPE_FAILED_EXTERNAL_NETWORK_DETAILS_CANNOT_BE_EDITED();

    String ACTION_TYPE_FAILED_EXTERNAL_NETWORK_CANNOT_BE_DISPLAY();

    String ACTION_TYPE_FAILED_EXTERNAL_NETWORK_CANNOT_BE_REQUIRED();

    String ACTION_TYPE_FAILED_EXTERNAL_NETWORK_WITH_VLAN_MUST_BE_CUSTOM();

    String ACTION_TYPE_FAILED_EXTERNAL_NETWORK_CANNOT_BE_PORT_MIRRORED();

    String ACTION_TYPE_FAILED_INVALID_VNIC_PROFILE_NETWORK_ID_CONFIGURATION();

    String ACTION_TYPE_FAILED_INVALID_VNIC_PROFILE_NETWORK_FILTER_ID();

    String ACTION_TYPE_FAILED_FAILOVER_VNIC_PROFILE_ID_IS_NOT_VALID();

    String ACTION_TYPE_FAILED_FAILOVER_IS_SUPPORTED_ONLY_FOR_MIGRATABLE_PASSTROUGH();

    String ACTION_TYPE_FAILED_UPDATE_OF_FAILOVER_PROFILE_IS_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_FAILOVER_VNIC_PROFILE_NOT_SUPPORTED_WITH_EXTERNAL_NETWORK();

    String ACTION_TYPE_FAILED_NIC_FILTER_PARAMETER_ID_NOT_EXISTS();

    String ACTION_TYPE_FAILED_INVALID_NIC_FILTER_PARAMETER_INTERFACE();

    String ACTION_TYPE_FAILED_INVALID_NIC_FILTER_PARAMETER_INTERFACE_VM();

    String ACTION_TYPE_FAILED_INVALID_NIC_FILTER_PARAMETER_NAME();

    String ACTION_TYPE_FAILED_INVALID_NIC_FILTER_PARAMETER_VALUE();

    String ACTION_TYPE_FAILED_PASSTHROUGH_PROFILE_CONTAINS_NOT_SUPPORTED_PROPERTIES();

    String ACTION_TYPE_FAILED_EXTERNAL_NETWORK_CANNOT_BE_REWIRED();

    String ACTION_TYPE_FAILED_MANAGEMENT_NETWORK_REQUIRED();

    String ACTION_TYPE_FAILED_NETWORK_ADDRESS_BRICK_IN_USE();

    String CANNOT_PREVIEW_ACTIVE_SNAPSHOT();

    String TAGS_SPECIFIED_TAG_CANNOT_BE_THE_PARENT_OF_ITSELF();

    String VM_CANNOT_MOVE_TO_CLUSTER_IN_OTHER_STORAGE_POOL();

    String VM_CLUSTER_IS_NOT_VALID();

    String NETWORK_CANNOT_REMOVE_MANAGEMENT_NETWORK();

    String ACTION_TYPE_FAILED_MANAGEMENT_NETWORK_UNSET();

    String ACTION_TYPE_FAILED_GLUSTER_NETWORK_INUSE();

    String NETWORK_CANNOT_REMOVE_ISCSI_BOND_NETWORK();

    String ACTION_TYPE_FAILED_DETECTED_ACTIVE_VMS();

    String ACTION_TYPE_FAILED_HOST_NOT_EXIST();

    String ACTION_TYPE_FAILED_VM_NOT_EXIST();

    String TAGS_SPECIFY_TAG_IS_IN_USE();

    String ACTION_LIST_CANNOT_BE_EMPTY();

    String ACTION_TYPE_FAILED_BOOKMARK_INVALID_ID();

    String ACTION_TYPE_FAILED_VDS_STATUS_ILLEGAL();

    String ACTION_TYPE_FAILED_MIGRATE_BETWEEN_TWO_CLUSTERS();

    String VDS_CANNOT_CHECK_VERSION_HOST_NON_RESPONSIVE();

    String ACTION_TYPE_FAILED_VDS_INTERMITENT_CONNECTIVITY();

    String ACTION_TYPE_FAILED_PM_ENABLED_WITHOUT_AGENT();

    String ACTION_TYPE_FAILED_PM_ENABLED_WITHOUT_AGENT_CREDENTIALS();

    String ACTION_TYPE_FAILED_AGENT_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_VM_CANNOT_IMPORT_VM_ARCHITECTURE_NOT_SUPPORTED_BY_CLUSTER();

    String ACTION_TYPE_FAILED_VM_CANNOT_IMPORT_TEMPLATE_ARCHITECTURE_NOT_SUPPORTED_BY_CLUSTER();

    String ACTION_TYPE_FAILED_VM_CANNOT_IMPORT_VM_WITH_NOT_SUPPORTED_ARCHITECTURE();

    String ACTION_TYPE_FAILED_VM_CANNOT_IMPORT_TEMPLATE_WITH_NOT_SUPPORTED_ARCHITECTURE();

    String ACTION_TYPE_FAILED_VDS_HA_NOT_CONFIGURED();

    String NETWORK_ALREADY_ATTACHED_TO_CLUSTER();

    String ACTION_TYPE_FAILED_VDS_WITH_SAME_HOST_EXIST();

    String ACTION_TYPE_FAILED_VDS_WITH_INVALID_SSH_PORT();

    String ACTION_TYPE_FAILED_VDS_WITH_INVALID_SSH_USERNAME();

    String ACTION_TYPE_FAILED_VDS_WITH_SAME_UUID_EXIST();

    String ACTION_TYPE_FAILED_ILLEGAL_NUM_OF_MONITORS();

    String ACTION_TYPE_FAILED_ILLEGAL_OS_TYPE_IS_NOT_SUPPORTED_BY_ARCHITECTURE_TYPE();

    String ACTION_TYPE_FAILED_ILLEGAL_WATCHDOG_MODEL_IS_NOT_SUPPORTED_BY_OS();

    String ACTION_TYPE_FAILED_ILLEGAL_VM_DISPLAY_TYPE_IS_NOT_SUPPORTED_BY_OS();

    String ACTION_TYPE_FAILED_ILLEGAL_VM_DISPLAY_TYPE_IS_NOT_SUPPORTED_BY_FIRMWARE();

    String ACTION_TYPE_FAILED_ILLEGAL_FLOPPY_IS_NOT_SUPPORTED_BY_OS();

    String ACTION_TYPE_FAILED_ILLEGAL_OS_TYPE_DOES_NOT_SUPPORT_VIRTIO_SCSI();

    String ACTION_TYPE_FAILED_SUSPEND_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_ILLEGAL_DOMAIN_NAME();

    String ACTION_TYPE_FAILED_CANNOT_DECREASE_DATA_CENTER_COMPATIBILITY_VERSION();

    String ACTION_TYPE_FAILED_CANNOT_DECREASE_CLUSTER_WITH_HOSTS_COMPATIBILITY_VERSION();

    String ACTION_TYPE_FAILED_DECREASING_COMPATIBILITY_VERSION_CAUSES_STORAGE_FORMAT_DOWNGRADING();

    String ACTION_TYPE_FAILED_CANNOT_DECREASE_COMPATIBILITY_VERSION_UNDER_DC();

    String ACTION_TYPE_FAILED_GIVEN_VERSION_NOT_SUPPORTED();

    String NETWORK_ADDR_MANDATORY_IN_STATIC_IP();

    String NETWORK_ADDR_MANDATORY_FOR_ROLE_NETWORK();

    String ACTION_TYPE_FAILED_OBJECT_LOCKED();

    String ACTION_TYPE_FAILED_PROVIDER_LOCKED();

    String ACTION_TYPE_FAILED_PROVIDER_URL_TENANT_COMBINATION_NOT_UNIQUE();

    String ACTION_TYPE_FAILED_PROVIDER_URL_PROJECT_NAME_AND_DOMAIN_NAME_COMBINATION_NOT_UNIQUE();

    String ACTION_TYPE_FAILED_NETWORK_IS_USED();

    String ACTION_TYPE_FAILED_VM_POOL_IS_USED_FOR_CREATE_VM();

    String ACTION_TYPE_FAILED_TEMPLATE_IS_USED_FOR_CREATE_VM();

    String ACTION_TYPE_FAILED_SNAPSHOT_IS_BEING_TAKEN_FOR_VM();

    String ACTION_TYPE_FAILED_VM_IS_HIBERNATING();

    String ACTION_TYPE_FAILED_DISK_IS_USED_FOR_CREATE_VM();

    String ACTION_TYPE_FAILED_DISK_IS_BEING_REMOVED();

    String ACTION_TYPE_FAILED_DOMAIN_OVF_ON_UPDATE();

    String ACTION_TYPE_FAILED_CANNOT_FIND_DISK_IMAGE_IN_ACTIVE_DOMAINS();

    String ACTION_TYPE_FAILED_DISK_IS_BEING_MIGRATED();

    String ACTION_TYPE_FAILED_DISK_IMAGE_CANNOT_BE_MEASURED_WHILE_USED();

    String ACTION_TYPE_FAILED_TEMPLATE_NAME_IS_USED();

    String ACTION_TYPE_FAILED_TEMPLATE_IS_BEING_CREATED();

    String ACTION_TYPE_FAILED_TEMPLATE_IS_BEING_CREATED_FROM_VM();

    String ACTION_TYPE_FAILED_TEMPLATE_VERSION_IS_BEING_CREATED();

    String ACTION_TYPE_FAILED_TEMPLATE_IS_BEING_EXPORTED();

    String ACTION_TYPE_FAILED_VM_IS_BEING_EXPORTED();

    String ACTION_TYPE_FAILED_NO_VALID_DOMAINS_STATUS_FOR_TEMPLATE_DISKS();

    String ACTION_TYPE_FAILED_VM_IS_BEING_IMPORTED();

    String ACTION_TYPE_FAILED_VM_IS_BEING_MIGRATED();

    String ACTION_TYPE_FAILED_TEMPLATE_IS_BEING_REMOVED();

    String ACTION_TYPE_FAILED_VM_IS_BEING_REMOVED_FROM_EXPORT_DOMAIN();

    String NETWORK_BOND_HAVE_ATTACHED_VLANS();

    String ACTION_TYPE_FAILED_DISK_MAX_SIZE_EXCEEDED();

    String VM_CANNOT_EXPORT_RAW_FORMAT();

    String VM_TEMPLATE_TPM_DATA_EXPORT_IS_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_TEMPLATE_NOT_FOUND_ON_EXPORT_DOMAIN();

    String ACTION_TYPE_FAILED_VM_NOT_FOUND_ON_EXPORT_DOMAIN();

    String ACTION_TYPE_FAILED_GENERATOR_NOT_SUPPORTED_BY_CLUSTER();

    String ACTION_TYPE_FAILED_MAX_CPU_PER_SOCKET();

    String ACTION_TYPE_FAILED_MAX_NUM_CPU();

    String ACTION_TYPE_FAILED_MIN_NUM_CPU_FOR_OS();

    String ACTION_TYPE_FAILED_MAX_NUM_SOCKETS();

    String VMT_CANNOT_IMPORT_TEMPLATE_EXISTS();

    String VMT_CANNOT_IMPORT_TEMPLATE_VERSION_MISSING_BASE();

    String VM_CANNOT_IMPORT_TEMPLATE_NAME_EXISTS();

    String VM_CANNOT_IMPORT_VM_EXISTS();

    String VM_CANNOT_IMPORT_VM_NAME_EXISTS();

    String TAGS_CANNOT_EDIT_READONLY_TAG();

    String VM_CANNOT_REMOVE_HAS_RUNNING_TASKS();

    String ACTION_TYPE_FAILED_IMPORTED_TEMPLATE_IS_MISSING();

    String VM_POOL_CANNOT_CREATE_WITH_NO_VMS();

    String ACTION_TYPE_FAILED_DISK_BOOT_IN_USE();

    String ACTION_TYPE_FAILED_PASS_DISCARD_NOT_SUPPORTED_BY_DISK_INTERFACE();

    String ACTION_TYPE_FAILED_PASS_DISCARD_NOT_SUPPORTED_FOR_DIRECT_LUN_BY_UNDERLYING_STORAGE();

    String ACTION_TYPE_FAILED_PASS_DISCARD_NOT_SUPPORTED_FOR_DISK_IMAGE_BY_UNDERLYING_STORAGE();

    String ACTION_TYPE_FAILED_PASS_DISCARD_NOT_SUPPORTED_BY_UNDERLYING_STORAGE_WHEN_WAD_IS_ENABLED();

    String ACTION_TYPE_FAILED_PASS_DISCARD_NOT_SUPPORTED_BY_STORAGE_TYPE();

    String ACTION_TYPE_FAILED_PASS_DISCARD_NOT_SUPPORTED_BY_DISK_STORAGE_TYPE();

    String ACTION_TYPE_FAILED_DISK_SPARSIFY_NOT_SUPPORTED_BY_DISK_STORAGE_TYPE();

    String ACTION_TYPE_FAILED_DISK_SPARSIFY_NOT_SUPPORTED_BY_STORAGE_TYPE();

    String ACTION_TYPE_FAILED_DISK_SPARSIFY_NOT_SUPPORTED_BY_UNDERLYING_STORAGE_WHEN_WAD_IS_ENABLED();

    String ACTION_TYPE_FAILED_DISK_SPARSIFY_NOT_SUPPORTED_FOR_PREALLOCATED();

    String ACTION_TYPE_FAILED_DISK_SPARSIFY_NOT_SUPPORTED_FOR_COW();

    String ACTION_TYPE_FAILED_DISCARD_AFTER_DELETE_NOT_SUPPORTED_BY_UNDERLYING_STORAGE();

    String ACTION_TYPE_FAILED_DISCARD_AFTER_DELETE_SUPPORTED_ONLY_BY_BLOCK_DOMAINS();

    String VM_OR_TEMPLATE_ILLEGAL_PRIORITY_VALUE();

    String ACTION_TYPE_FAILED_MIN_CPU_PER_SOCKET();

    String ACTION_TYPE_FAILED_MIN_NUM_SOCKETS();

    String ACTION_TYPE_FAILED_SPECIFY_DOMAIN_IS_NOT_EXPORT_DOMAIN();

    String IPV4_ADDR_BAD_FORMAT();

    String BAD_IPV6_ADDRESS_FORMAT();

    String IPV4_ADDR_GATEWAY_BAD_FORMAT();

    String NETWORK_ADDR_IN_SUBNET_BAD_FORMAT();

    String UPDATE_NETWORK_ADDR_IN_SUBNET_BAD_VALUE();

    String UPDATE_NETWORK_ADDR_IN_SUBNET_BAD_FORMAT();

    String NETWORK_BOND_NAME_BAD_FORMAT();

    String NETWORK_CANNOT_CONTAIN_BOND_NAME();

    String RHEVH_LOCALFS_WRONG_PATH_LOCATION();

    String ACTION_TYPE_FAILED_STORAGE_POOL_IS_NOT_LOCAL();

    String VDS_CANNOT_ADD_MORE_THEN_ONE_HOST_TO_LOCAL_STORAGE();

    String VDS_CANNOT_REMOVE_HOST_WITH_LOCAL_STORAGE();

    String CLUSTER_CANNOT_ADD_MORE_THEN_ONE_HOST_TO_LOCAL_STORAGE();

    String CLUSTER_SELECTION_ALGORITHM_MUST_BE_SET_TO_NONE_ON_LOCAL_STORAGE();

    String CLUSTER_CANNOT_DETACH_DATA_DOMAIN_FROM_LOCAL_STORAGE();

    String ACTION_TYPE_FAILED_CINDER_ALREADY_EXISTS();

    String VDS_CANNOT_UPDATE_CLUSTER();

    String VM_CANNOT_UPDATE_CLUSTER();

    String VM_STATUS_NOT_VALID_FOR_UPDATE();

    String PERMISSION_ADD_FAILED_PERMISSION_NOT_SENT();

    String PERMISSION_ADD_FAILED_INVALID_ROLE_ID();

    String PERMISSION_ADD_FAILED_INVALID_OBJECT_ID();

    String PERMISSION_ADD_FAILED_USER_ID_MISMATCH();

    String PERMISSION_ADD_FAILED_ONLY_SYSTEM_SUPER_USER_CAN_GIVE_ADMIN_ROLES();

    String PERMISSION_REMOVE_FAILED_ONLY_SYSTEM_SUPER_USER_CAN_REMOVE_ADMIN_ROLES();

    String PERMISSION_ADD_FAILED_VM_IN_POOL();

    String SYSTEM_PERMISSIONS_CANT_BE_REMOVED_FROM_EVERYONE();

    String CLUSTER_CPU_UTILIZATION_MUST_BE_IN_VALID_RANGE();

    String CLUSTER_CPU_LOW_UTILIZATION_PERCENTAGE_MUST_BE_LOWER_THAN_HIGH_PERCENTAGE();

    String CLUSTER_CPU_HIGH_UTILIZATION_PERCENTAGE_MUST_BE_DEFINED_WHEN_USING_EVENLY_DISTRIBUTED();

    String CLUSTER_BOTH_LOW_AND_HIGH_CPU_UTILIZATION_PERCENTAGE_MUST_BE_DEFINED_WHEN_USING_POWER_SAVING();

    String NETWORK_ATTACH_ILLEGAL_GATEWAY();

    String SLAVE_INTERFACE_IS_MISCONFIGURED();

    String IMPROPER_INTERFACE_IS_LABELED();

    String IMPROPER_BOND_IS_LABELED();

    String INTERFACE_ALREADY_LABELED();

    String NETWORK_INTERFACE_IS_NOT_BOND();

    String INTERFACE_NOT_LABELED();

    String MISSING_DIRECTORY_ELEMENT_ID();

    String NETWORK_ILEGAL_NETWORK_NAME();

    String NETWORK_INTERFACE_NAME_ALREADY_IN_USE();

    String VALIDATION_TAGS_INVALID_TAG_NAME();

    String VALIDATION_VM_POOLS_NAME_NOT_NULL();

    String VALIDATION_VM_POOLS_SPICE_PROXY_HOSTNAME_OR_IP();

    String VALIDATION_ROLES_NAME_NOT_NULL();

    String VALIDATION_ROLES_NAME_MAX();

    String VALIDATION_CLUSTER_NAME_NOT_NULL();

    String VALIDATION_CLUSTER_NAME_MAX();

    String VALIDATION_CLUSTER_MIGRATE_ON_ERROR_NOT_NULL();

    String VALIDATION_CLUSTER_SPICE_PROXY_HOSTNAME_OR_IP();

    String VALIDATION_STORAGE_POOL_ID_NOT_NULL();

    String VALIDATION_VDS_HOSTNAME_HOSTNAME_OR_IP();

    String VALIDATION_VDS_POWER_MGMT_ADDRESS_HOSTNAME_OR_IP();

    String VALIDATION_VM_NUM_OF_MONITORS_EXCEEDED();

    String VALIDATION_VM_TEMPLATE_NAME_MAX();

    String VALIDATION_DISK_INTERFACE_NOT_NULL();

    String VALIDATION_VOLUME_TYPE_NOT_NULL();

    String VALIDATION_DISK_ALIAS_INVALID();

    String VALIDATION_VOLUME_FORMAT_NOT_NULL();

    String VALIDATION_DISK_IMAGE_DESCRIPTION_NOT_EMPTY();

    String VALIDATION_DISK_IMAGE_DESCRIPTION_MAX();

    String VALIDATION_DATA_CENTER_DESCRIPTION_INVALID();

    String VALIDATION_VDS_NAME_INVALID();

    String VALIDATION_EVENTS_EMAIL_FORMAT();

    String VALIDATION_INVALID_CORRELATION_ID();

    String VALIDATION_ROLES_NAME_INVALID();

    String VALIDATION_CLUSTER_NAME_INVALID();

    String VALIDATION_STORAGE_DOMAIN_NAME_INVALID();

    String VALIDATION_STORAGE_DOMAIN_DESCRIPTION_INVALID();

    String VALIDATION_STORAGE_DOMAIN_DESCRIPTION_MAX();

    String VALIDATION_STORAGE_DOMAIN_WARNING_LOW_SPACE_INDICATOR_RANGE();

    String VALIDATION_STORAGE_DOMAIN_CRITICAL_SPACE_ACTION_BLOCKER_RANGE();

    String VALIDATION_STORAGE_DOMAIN_WARNING_LOW_CONFIRMED_SPACE_INDICATOR_RANGE();

    String VALIDATION_DATA_CENTER_NAME_INVALID();

    String VALIDATION_ID_NULL();

    String VALIDATION_NETWORK_ID_OR_NETWORK_NAME_MUST_BE_SET();

    String NETWORK_ATTACHMENTS_ID_MUST_BE_SET_FOR_UPDATE();

    String NIC_LABEL_VALIDATION_NIC_ID_OR_NIC_NAME_MUST_BE_SET();

    String LABEL_ON_NETWORK_LABEL_CANNOT_BE_NULL();

    String VALIDATION_NAME_NULL();

    String VALIDATION_NAME_INVALID();

    String VALIDATION_NAME_INVALID_WITH_DOT();

    String VALIDATION_URL_NULL();

    String VALIDATION_URL_INVALID();

    String VALIDATION_PROVIDER_TYPE_NULL();

    String VALIDATION_QUOTA_NAME_INVALID();

    String VALIDATION_VM_NETWORK_MAC_ADDRESS_INVALID();

    String VALIDATION_VM_NETWORK_MAC_ADDRESS_MULTICAST();

    String VALIDATION_VM_NETWORK_MAC_ADDRESS_NOT_NULL();

    String VALIDATION_VM_NETWORK_NAME_NOT_NULL();

    String VALIDATION_CONNECTIVITY_TIMEOUT_INVALID();

    String VALIDATION_REPETITIVE_IP_IN_VDS();

    String VALIDATION_VDS_PORT_RANGE();

    String ERROR_CANNOT_FIND_ISO_IMAGE_PATH();

    String ERROR_CANNOT_REMOVE_SNAPSHOT_ILLEGAL_IMAGE();

    String ERROR_ISO_IMAGE_STATUS_ILLEGAL();

    String ERROR_CANNOT_FIND_FLOPPY_IMAGE_PATH();

    String VDS_ADD_STORAGE_SERVER_STATUS_MUST_BE_UP();

    String USER_FAILED_TO_AUTHENTICATE_WRONG_USERNAME_OR_PASSWORD();

    String CLUSTER_CANNOT_UPDATE_CPU_WITH_SUSPENDED_VMS();

    String CLUSTER_CPU_IS_NOT_UPDATABLE();

    String USER_FAILED_TO_AUTHENTICATE_ACCOUNT_IS_LOCKED_OR_DISABLED();

    String ACTION_TYPE_FAILED_INVALID_CUSTOM_PROPERTIES_DUPLICATE_KEYS();

    String ACTION_TYPE_FAILED_HOSTNAME_CANNOT_CHANGE();

    String CAN_DO_ACTION_DATABASE_CONNECTION_FAILURE();

    String ACTION_TYPE_FAILED_DESCRIPTION_MAY_NOT_CONTAIN_SPECIAL_CHARS();

    String ACTION_TYPE_FAILED_LINUX_BOOT_PARAMS_MAY_NOT_CONTAIN_TRIMMING_WHITESPACES();

    String ACTION_TYPE_FAILED_NAME_LENGTH_IS_TOO_LONG();

    String ACTION_TYPE_FAILED_NAME_MAY_NOT_BE_EMPTY();

    String ACTION_TYPE_FAILED_TEMPLATE_IS_INCOMPATIBLE();

    String ACTION_TYPE_FAILED_NAME_MAY_NOT_CONTAIN_SPECIAL_CHARS();

    String ACTION_TYPE_FAILED_INVALID_VDS_HOSTNAME();

    String VM_CANNOT_RUN_ONCE_WITH_ILLEGAL_SYSPREP_PARAM();

    String ACTION_TYPE_FAILED_CANNOT_REMOVE_BUILTIN_GROUP_EVERYONE();

    String ACTION_TYPE_FAILED_IMPORT_DATA_DOMAIN_IS_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_RESET_VM_IS_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_SCREENSHOT_VM_IS_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_VDS_NOT_MATCH_VALID_STATUS();

    String CANNOT_REMOVE_STORAGE_DOMAIN_INVALID_HOST_ID();

    String CANNOT_REMOVE_STORAGE_DOMAIN_HOST_NOT_UP();

    String ERROR_CANNOT_DEACTIVATE_MASTER_WITH_LOCKED_DOMAINS();

    String TAGS_CANNOT_REMOVE_TAG_NOT_EXIST();

    String AUDIT_LOG_CANNOT_REMOVE_AUDIT_LOG_NOT_EXIST();

    String VAR__TYPE__VM__CLUSTER();

    String VDS_FENCE_OPERATION_FAILED();

    String ERROR_CANNOT_DEACTIVATE_STORAGE_DOMAIN_WITH_ISO_ATTACHED();

    String ERROR_CANNOT_DEACTIVATE_STORAGE_DOMAIN_DURING_UPLOAD_OR_DOWNLOAD();

    String ERROR_CANNOT_REMOVE_ISO_DISK_ATTACHED_TO_VMS();

    String ERROR_ISO_DISK_ATTACHED_TO_RUNNING_VMS();

    String CAN_DO_ACTION_GENERAL_FAILURE();

    String ERROR_CANNOT_REMOVE_ACTIVE_STORAGE_POOL();

    String ROLE_TYPE_CANNOT_BE_EMPTY();

    String CANNOT_ADD_ACTION_GROUPS_TO_ROLE_TYPE();

    String STORAGE_DOMAIN_NOT_ATTACHED_TO_STORAGE_POOL();

    String VDS_APPROVE_VDS_NOT_FOUND();

    String ACTION_TYPE_FAILED_QUOTA_NULL_NOT_ALLOWED();

    String ACTION_TYPE_FAILED_QUOTA_NOT_EXIST();

    String ACTION_TYPE_FAILED_QUOTA_IS_NOT_VALID();

    String ACTION_TYPE_FAILED_QUOTA_DEFAULT_CANNOT_BE_CHANGED();

    String ACTION_TYPE_FAILED_QUOTA_NOT_DEFINED_FOR_DOMAIN();

    String ACTION_TYPE_FAILED_QUOTA_NOT_DEFINED_FOR_CLUSTER();

    String ACTION_TYPE_FAILED_NO_QUOTA_SET_FOR_DOMAIN();

    String ACTION_TYPE_FAILED_QUOTA_IS_NO_LONGER_AVAILABLE_IN_SYSTEM();

    String ACTION_TYPE_FAILED_QUOTA_LIMIT_IS_SPECIFIC_AND_GENERAL();

    String ACTION_TYPE_FAILED_QUOTA_IN_USE_BY_VM_OR_DISK();

    String ACTION_TYPE_FAILED_QUOTA_STORAGE_LIMIT_EXCEEDED();

    String ACTION_TYPE_FAILED_QUOTA_CLUSTER_LIMIT_EXCEEDED();

    String USER_NOT_AUTHORIZED_TO_CONSUME_QUOTA();

    String USER_CANNOT_RUN_QUERY_NOT_PUBLIC();

    String USER_CANNOT_RUN_ACTION_INTERNAL_COMMAND();

    String ERROR_CANNOT_ATTACH_ACTION_GROUP_TO_ROLE_ATTACHED();

    String ERROR_CANNOT_DETACH_ACTION_GROUP_TO_ROLE_NOT_ATTACHED();

    String VDS_CANNOT_CONNECT_TO_SERVER();

    String VDS_CANNOT_AUTHENTICATE_TO_SERVER();

    String VDS_SECURITY_CONNECTION_ERROR();

    String ERROR_CANNOT_ADD_STORAGE_POOL_WITHOUT_DATA_AND_ISO_DOMAINS();

    String ERROR_CANNOT_ADD_STORAGE_POOL_WITH_DIFFERENT_STORAGE_FORMAT();

    String EN_UNKNOWN_TAG_NAME();

    String ERROR_CANNOT_REMOVE_POOL_WITH_NETWORKS();

    String ACTION_TYPE_FAILED_NETWORK_LABEL_RENAMING_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_DETECTED_PINNED_VMS();

    String ACTION_TYPE_FAILED_DETECTED_ASSIGNED_HOST_DEVICES();

    String HOT_PLUG_CPU_IS_NOT_SUPPORTED();

    String HOT_PLUG_CPU_IS_NOT_SUPPORTED_FOR_GUEST_OS();

    String HOT_UNPLUG_CPU_IS_NOT_SUPPORTED();

    String HOT_UNPLUG_CPU_IS_NOT_SUPPORTED_FOR_GUEST_OS();

    String HOT_PLUG_MEMORY_IS_NOT_SUPPORTED();

    String HOT_CHANGE_MEMORY_WITH_NEXT_RUN();

    String HOT_UNPLUG_MEMORY_IS_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_NO_MORE_MEMORY_SLOTS();

    String ACTION_TYPE_FAILED_MEMORY_MUST_BE_MULTIPLICATION();

    String HOT_PLUG_IDE_DISK_IS_NOT_SUPPORTED();

    String HOT_PLUG_SPAPR_VSCSI_DISK_IS_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_UNLINKING_OF_PASSTHROUGH_VNIC_IS_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_NETWORK_QOS_IS_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_VM_INTERFACE_TYPE_IS_NOT_SUPPORTED_BY_OS();

    String ACTION_TYPE_FAILED_VM_INTERFACE_TYPE_NOT_MATCH_PROFILE();

    String ACTION_TYPE_FAILED_ONLY_EXTERNAL_NETWORK_IS_SUPPORTED_IN_OVS_SWITCH_TYPE();

    String ACTION_TYPE_FAILED_VM_INTERFACE_WITH_FAILOVER_IS_SUPPORTED_ONLY_IN_CLUSTER_4_6_AND_ABOVE();

    String CANNOT_PERFORM_HOT_UPDATE();

    String CANNOT_PERFORM_HOT_UPDATE_WITH_PORT_MIRRORING();

    String PORT_MIRRORING_REQUIRES_NETWORK();

    String ACTION_TYPE_FAILED_GUEST_OS_VERSION_IS_NOT_SUPPORTED();

    String HOT_PLUG_DISK_IS_NOT_VIRTIO();

    String HOT_PLUG_DISK_IS_NOT_UNPLUGGED();

    String CANNOT_ADD_FLOATING_DISK_WITH_PLUG_VM_SET();

    String DEACTIVATE_MANAGEMENT_NETWORK_FOR_HOSTED_ENGINE();

    String HOSTED_ENGINE_VM_CANNOT_HAVE_NIC_WITH_EMPTY_PROFILE();

    String ACTIVATE_DEACTIVATE_NETWORK_NOT_IN_VDS();

    String HOT_UNPLUG_DISK_IS_NOT_PLUGGED();

    String SHAREABLE_DISK_IS_NOT_SUPPORTED_FOR_DISK();

    String SHAREABLE_DISK_IS_NOT_SUPPORTED_BY_VOLUME_FORMAT();

    String ACTION_TYPE_FAILED_THIN_TEMPLATE_DISKS_SHOULD_ONLY_BE_COW();

    String ERROR_CANNOT_DETACH_DISK_WITH_SNAPSHOT();

    String DISK_IS_ALREADY_SHARED_BETWEEN_VMS();

    String VM_CANNOT_RUN_FROM_DISK_WITHOUT_PLUGGED_DISK();

    String SCSI_GENERIC_IO_IS_NOT_SUPPORTED_FOR_IMAGE_DISK();

    String SCSI_PASSTHROUGH_IS_NOT_SUPPORTED_FOR_READ_ONLY_DISK();

    String CANNOT_PERFORM_ACTION_VIRTIO_SCSI_IS_DISABLED();

    String CANNOT_DISABLE_VIRTIO_SCSI_PLUGGED_DISKS();

    String USER_PASSWORD_EXPIRED();

    String USER_PASSWORD_EXPIRED_CHANGE_URL_PROVIDED();

    String USER_PASSWORD_EXPIRED_CHANGE_MSG_PROVIDED();

    String USER_CANNOT_LOGIN_DOMAIN_NOT_SUPPORTED();

    String VM_POOL_CANNOT_DECREASE_VMS_FROM_POOL();

    String VM_POOL_CANNOT_ATTACH_TO_MORE_VMS_FROM_POOL();

    String VM_POOL_CANNOT_CHANGE_POOL_TYPE();

    String VM_POOL_CANNOT_CHANGE_TEMPLATE_WHEN_DELETE_PROTECTED();

    String VM_POOL_CANNOT_CHANGE_POOL_STATEFUL_OPTION();

    String VM_POOL_CANNOT_CHANGE_AUTO_STORAGE_SELECT();

    String VM_POOL_CANNOT_CHANGE_POOL_NAME();

    String MOVE_VM_CLUSTER_MISSING_NETWORK();

    String ACTION_TYPE_FAILED_STORAGE_POOL_WITH_DEFAULT_CLUSTER_CANNOT_BE_LOCALFS();

    String DEFAULT_CLUSTER_CANNOT_BE_ON_LOCALFS();

    String VM_CANNOT_CANCEL_MIGRATION_WHEN_VM_IS_NOT_MIGRATING();

    String VM_CANNOT_CANCEL_CONVERSION_WHEN_VM_IS_NOT_BEING_CONVERTED();

    String ACTION_TYPE_FAILED_VM_SNAPSHOT_NOT_IN_PREVIEW();

    String ACTION_TYPE_FAILED_VM_SNAPSHOT_IMAGE_ALREADY_EXISTS();

    String ACTION_TYPE_FAILED_SHAREABLE_DISK_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_DISK_NOT_EXIST();

    String ACTION_TYPE_FAILED_DISK_NOT_ATTACHED_TO_VM();

    String ACTION_TYPE_FAILED_CANNOT_DETACH_DISK_IS_NOT_ATTACHED_TO_VM();

    String ACTION_TYPE_FAILED_DISK_PLUGGED_TO_NON_DOWN_VMS();

    String ACTION_TYPE_FAILED_DISKS_NOT_ATTACHED_TO_VM();

    String ACTION_TYPE_FAILED_DISK_VM_DATA_MISSING();

    String ACTION_TYPE_FAILED_DISKS_NOT_EXIST();

    String ACTION_TYPE_FAILED_DISK_SNAPSHOTS_NOT_EXIST();

    String ACTION_TYPE_FAILED_DISK_SNAPSHOTS_ACTIVE();

    String ACTION_TYPE_FAILED_DISK_SNAPSHOT_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_DAMAGED_IMAGE_SNAPSHOT();

    String ACTION_TYPE_FAILED_NO_DISKS_SPECIFIED();

    String ACTION_TYPE_FAILED_NO_DISKS_IMAGE();

    String ACTION_TYPE_FAILED_CANT_MOVE_SHAREABLE_DISK_TO_GLUSTERFS();

    String ACTION_TYPE_FAILED_CANT_MOVE_OR_COPY_SHAREABLE_THIN_DISK_TO_BLOCK_DOMAIN();

    String ACTION_TYPE_FAILED_SOURCE_AND_TARGET_SAME();

    String ACTION_TYPE_FAILED_BASE_TEMPLATE_DOES_NOT_EXIST();

    String ACTION_TYPE_FAILED_NOT_A_VM_NETWORK();

    String ACTION_TYPE_FAILED_NETWORK_NOT_IN_CLUSTER();

    String NON_VM_NETWORK_NOT_SUPPORTED_FOR_POOL_LEVEL();

    String GLUSTER_NETWORK_NOT_SUPPORTED_FOR_POOL_LEVEL();

    String VALIDATION_DISK_DESCRIPTION_INVALID();

    String VALIDATION_DISK_IMAGE_DESCRIPTION_INVALID();

    String VALIDATION_STORAGE_CONNECTION_EMPTY_VFSTYPE();

    String VALIDATION_STORAGE_CONNECTION_MOUNT_OPTIONS_CONTAINS_MANAGED_PROPERTY();

    String VALIDATION_STORAGE_CONNECTION_EMPTY_IQN();

    String VALIDATION_STORAGE_CONNECTION_EMPTY_CONNECTION();

    String VALIDATION_STORAGE_CONNECTION_INVALID();

    String VALIDATION_STORAGE_CONNECTION_INVALID_PORT();

    String VALIDATION_STORAGE_CONNECTION_NFS_RETRANS();

    String VALIDATION_STORAGE_CONNECTION_NFS_TIMEO();

    String VMPAYLOAD_INVALID_PAYLOAD_TYPE();

    String VMPAYLOAD_SIZE_EXCEEDED();

    String VMPAYLOAD_FLOPPY_EXCEEDED();

    String VMPAYLOAD_FLOPPY_WITH_SYSPREP();

    String VMPAYLOAD_CDROM_WITH_CLOUD_INIT();

    String VMPAYLOAD_CDROM_OR_CLOUD_INIT_MAXIMUM_DEVICES();

    String ACTION_TYPE_FAILED_CLUSTER_IS_NOT_VALID();

    String ACTION_TYPE_FAILED_CLUSTER_DOES_NOT_SUPPORT_GLUSTER();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_NAME_ALREADY_EXISTS();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_INVALID();

    String ACTION_TYPE_FAILED_BRICKS_REQUIRED();

    String ACTION_TYPE_FAILED_GLUSTER_ARBITER_VOLUME_SHOULD_BE_REPLICA_3_VOLUME();

    String ACTION_TYPE_FAILED_REPLICA_COUNT_MIN_2();

    String ACTION_TYPE_FAILED_INVALID_BRICK_COUNT_FOR_DISTRIBUTED_REPLICATE();

    String ACTION_TYPE_FAILED_INVALID_BRICK_COUNT_FOR_REPLICATE();

    String ACTION_TYPE_FAILED_STRIPE_COUNT_MIN_4();

    String ACTION_TYPE_FAILED_INVALID_BRICK_COUNT_FOR_STRIPE();

    String ACTION_TYPE_FAILED_INVALID_BRICK_COUNT_FOR_DISTRIBUTED_STRIPE();

    String ACTION_TYPE_FAILED_INVALID_BRICK_COUNT_FOR_STRIPED_REPLICATE();

    String ACTION_TYPE_FAILED_INVALID_BRICK_COUNT_FOR_DISTRIBUTED_STRIPED_REPLICATE();

    String ACTION_TYPE_FAILED_INVALID_BRICK_SERVER_ID();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_ALREADY_STARTED();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_ALREADY_STOPPED();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_IS_UP();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_HAS_SNAPSHOTS();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_IS_DOWN();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_IS_NOT_THINLY_PROVISIONED();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_SNAPSHOT_CONFIG_PARAMS_IS_EMPTY();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_SNAPSHOT_CONFIG_PARAM_VALUE_IS_EMPTY();

    String ACTION_TYPE_NOT_SUPPORTED_FOR_VOLUME_TYPE();

    String ACTION_TYPE_FAILED_START_DATE_BEFORE_CURRENT_DATE();

    String ACTION_TYPE_FAILED_END_BY_DATE_BEFORE_CURRENT_DATE();

    String ACTION_TYPE_FAILED_END_BY_DATE_BEFORE_START_DATE();

    String ACTION_TYPE_FAILED_CAN_NOT_REMOVE_ALL_BRICKS_FROM_VOLUME();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_REMOVE_BRICKS_NOT_STARTED();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_INVALID_TASK_TYPE();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_REMOVE_BRICKS_PARAMS_INVALID();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_REMOVE_BRICKS_NOT_FINISHED();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_SHOULD_BE_STARTED();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_NOT_DISTRIBUTED();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_DISTRIBUTED_AND_HAS_SINGLE_BRICK();

    String ACTION_TYPE_FAILED_NOT_A_GLUSTER_VOLUME_BRICK();

    String VDS_CANNOT_REMOVE_HOST_HAVING_GLUSTER_VOLUME();

    String ACTION_TYPE_FAILED_NO_GLUSTER_HOST_TO_PEER_PROBE();

    String ACTION_TYPE_FAILED_GLUSTER_BRICK_INVALID();

    String ACTION_TYPE_FAILED_BRICK_ID_REQUIRED();

    String ACTION_TYPE_FAILED_ONE_OR_MORE_BRICKS_ARE_DOWN();

    String ACTION_TYPE_FAILED_REPLICASET_SAME_SERVER();

    String ACTION_TYPE_FAILED_CAN_NOT_REDUCE_REPLICA_COUNT_MORE_THAN_ONE();

    String ACTION_TYPE_FAILED_CAN_NOT_REDUCE_REPLICA_COUNT_WITH_DATA_MIGRATION();

    String ACTION_TYPE_FAILED_CAN_NOT_INCREASE_REPLICA_COUNT();

    String ACTION_TYPE_FAILED_CAN_NOT_REDUCE_REPLICA_COUNT();

    String ACTION_TYPE_FAILED_CAN_NOT_INCREASE_REPLICA_COUNT_MORE_THAN_ONE();

    String ACTION_TYPE_FAILED_CAN_NOT_INCREASE_STRIPE_COUNT_MORE_THAN_ONE();

    String ACTION_TYPE_FAILED_CAN_NOT_REDUCE_STRIPE_COUNT();

    String ACTION_TYPE_FAILED_DUPLICATE_BRICKS();

    String ACTION_TYPE_FAILED_ADD_BRICK_TO_DISPERSE_VOLUME_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_ADD_BRICK_TO_DISTRIBUTED_DISPERSE_VOLUME_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_REMOVE_BRICK_FROM_DISPERSE_VOLUME_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_REMOVE_BRICK_FROM_DISTRIBUTED_DISPERSE_VOLUME_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_CREATION_OF_DISPERSE_VOLUME_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_BRICK_ALREADY_EXISTS_IN_VOLUME();

    String ACTION_TYPE_FAILED_NO_UP_SERVER_FOUND();

    String ACTION_TYPE_FAILED_VOLUME_OPERATION_IN_PROGRESS();

    String ACTION_TYPE_FAILED_CUSTOM_COMPATIBILITY_VERSION_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_MEMORY_TOO_OLD();

    String ACTION_TYPE_FAILED_INVALID_CREATION_DATE();

    String ACTION_TYPE_FAILED_VOLUME_ASYNC_OPERATION_IN_PROGRESS();

    String ACTION_TYPE_FAILED_IMAGE_DOWNLOAD_ERROR();

    String ACTION_TYPE_FAILED_CANNOT_FIND_SPECIFIED_IMAGE();

    String ACTION_TYPE_FAILED_CANNOT_IMPORT_IMAGE_FROM_REPOSITORY();

    String ACTION_TYPE_FAILED_IMAGE_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_IMAGE_UNRECOGNIZED();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_REBALANCE_NOT_STARTED();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_CANNOT_STOP_REBALANCE_IN_PROGRESS();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_CANNOT_STOP_REMOVE_BRICK_IN_PROGRESS();

    String ACTION_TYPE_FAILED_SNAPSHOT_ALREADY_EXISTS();

    String ACTION_TYPE_FAILED_NETWORK_INTERFACE_MAC_INVALID();

    String ACTION_TYPE_FAILED_TAG_ID_REQUIRED();

    String MIGRATE_PAUSED_EIO_VM_IS_NOT_SUPPORTED();

    String VM_INTERFACE_NOT_EXIST();

    String HOST_NETWORK_INTERFACE_NOT_EXIST();

    String HOST_NETWORK_INTERFACE_HAVING_ID_OR_NAME_DOES_NOT_EXIST();

    String HOST_NETWORK_INTERFACE_HAVING_NAME_DOES_NOT_EXIST();

    String NETWORK_OF_GIVEN_NAME_NOT_EXISTS_IN_CLUSTER();

    String HOST_NETWORK_INTERFACE_HAVING_ID_DOES_NOT_EXIST();

    String HOST_NETWORK_INTERFACE_DOES_NOT_HAVE_NAME_SET();

    String BOND_DOES_NOT_HAVE_NEITHER_ID_NOR_NAME_SPECIFIED();

    String BONDS_UPDATED_AND_REMOVED_SIMULTANEOUSLY();

    String ACTION_TYPE_FAILED_CANNOT_REMOVE_ACTIVE_DEVICE();

    String ACTION_TYPE_FAILED_IMPORT_CLONE_NOT_COLLAPSED();

    String ACTION_TYPE_FAILED_IMPORT_UNREGISTERED_NOT_COLLAPSED();

    String CLUSTER_ENABLING_BOTH_VIRT_AND_GLUSTER_SERVICES_NOT_ALLOWED();

    String USER_CANNOT_FORCE_RECONNECT_TO_VM();

    String ENGINE_IS_RUNNING_IN_MAINTENANCE_MODE();

    String ENGINE_IS_RUNNING_IN_PREPARE_MODE();

    String VAR__TYPE__EXTERNAL_EVENT();

    String ACTION_TYPE_FAILED_EXTERNAL_EVENT_ILLEGAL_ORIGIN();

    String ACTION_TYPE_FAILED_EXTERNAL_EVENT_NOT_FOUND();

    String ACTION_TYPE_FAILED_EXTERNAL_EVENT_DUPLICATE_CUSTOM_ID();

    String VAR__TYPE__EXTERNAL_JOB();

    String VAR__TYPE__EXTERNAL_STEP();

    String VAR__ACTION__END();

    String VAR__ACTION__CLEAR();

    String ACTION_TYPE_EMPTY_DESCRIPTION();

    String ACTION_TYPE_NOT_EXTERNAL();

    String ACTION_TYPE_NO_PARENT();

    String ACTION_TYPE_NO_JOB();

    String ACTION_TYPE_NO_STEP();

    String ACTION_TYPE_NON_MONITORED();

    String ACTION_TYPE_FAILED_GLUSTER_HOOK_ID_IS_REQUIRED();

    String ACTION_TYPE_FAILED_GLUSTER_HOOK_DOES_NOT_EXIST();

    String SERVER_ALREADY_EXISTS_IN_ANOTHER_CLUSTER();

    String SERVER_ALREADY_PART_OF_ANOTHER_CLUSTER();

    String SSH_AUTHENTICATION_FAILED();

    String GLUSTER_VOLUME_ID_INVALID();

    String FAILED_TO_RUN_LDAP_QUERY();

    String ACTION_TYPE_FAILED_GLUSTER_HOOK_NO_CONFLICT_SERVERS();

    String ACTION_TYPE_FAILED_SERVER_STATUS_NOT_UP();

    String CLUSTER_ALL_SERVERS_NOT_UP();

    String ACTION_TYPE_FAILED_GLUSTER_OPERATION_INPROGRESS();

    String ACTION_TYPE_FAILED_GEOREP_SESSION_INVALID();

    String ACTION_TYPE_FAILED_ONE_OR_MORE_REMOTE_HOSTS_ARE_NOT_ACCESSIBLE();

    String ACTION_TYPE_FAILED_GLUSTER_NO_PUB_KEYS_PASSED();

    String ACTION_TYPE_FAILED_GLUSTER_GEOREP_SESSION_ALREADY_CREATED();

    String ACTION_TYPE_FAILED_GEOREP_SESSION_ALREADY_STARTED();

    String ACTION_TYPE_FAILED_GEOREP_SESSION_LOCKED();

    String ACTION_TYPE_FAILED_GEOREP_SESSION_STOPPED();

    String ACTION_TYPE_FAILED_GEOREP_SESSION_ALREADY_RESUMED();

    String ACTION_TYPE_FAILED_GEOREP_SESSION_ALREADY_PAUSED();

    String ACTION_TYPE_FAILED_GLUSTER_GEOREP_CONFIG_SET();

    String ACTION_TYPE_FAILED_GLUSTER_GEOREP_CONFIG_DEFAULT_SET();

    String ACTION_TYPE_FAILED_REMOTE_CLUSTER_NOT_MAINTAINED_BY_ENGINE();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_SNAPSHOT_NAME_IS_EMPTY();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_SNAPSHOT_DOES_NOT_EXIST();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_NO_SNAPSHOTS_EXIST();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_SNAPSHOT_ALREADY_ACTIVATED();

    String ACTION_TYPE_FAILED_GLUSTER_VOLUME_SNAPSHOT_ALREADY_DEACTIVATED();

    String ACTION_TYPE_FAILED_GLUSTER_CLI_SCHEDULING_ENABLED();

    String ACTION_TYPE_FAILED_STORAGE_PROVISIONING_NOT_SUPPORTED_BY_CLUSTER();

    String ACTION_TYPE_FAILED_GLUSTER_SERVICE_MAINTENANCE_NOT_SUPPORTED_FOR_CLUSTER();

    String ACTION_TYPE_FAILED_STORAGE_DEVICE_LOCKED();

    String ACTION_TYPE_FAILED_STORAGE_DEVICE_REQUIRED();

    String ACTION_TYPE_FAILED_DIFFERENT_STORAGE_DEVICE_TYPES_SELECTED();

    String ACTION_TYPE_FAILED_DEVICE_IS_ALREADY_IN_USE();

    String ACTION_TYPE_FAILED_NETWORK_QOS_MISSING_VALUES();

    String ACTION_TYPE_FAILED_NETWORK_QOS_NEGATIVE_VALUES();

    String ACTION_TYPE_FAILED_NETWORK_QOS_NAME_EXIST();

    String ACTION_TYPE_FAILED_NETWORK_QOS_MISSING_DATA();

    String ACTION_TYPE_FAILED_NETWORK_QOS_NOT_FOUND();

    String ACTION_TYPE_FAILED_NETWORK_QOS_INVALID_DC_ID();

    String ACTION_TYPE_FAILED_NETWORK_QOS_PEAK_LOWER_THAN_AVERAGE();

    String ACTION_TYPE_FAILED_HOST_NETWORK_QOS_MISSING_VALUES();

    String ACTION_TYPE_FAILED_HOST_NETWORK_QOS_SETUP_NETWORKS_MISSING_VALUES();

    String ACTION_TYPE_FAILED_HOST_NETWORK_QOS_INCONSISTENT_VALUES();

    String ACTION_TYPE_FAILED_HOST_NETWORK_QOS_SETUP_NETWORKS_INCONSISTENT_VALUES();

    String ACTION_TYPE_FAILED_HOST_NETWORK_QOS_INTERFACES_WITHOUT_QOS();

    String ACTION_TYPE_FAILED_HOST_NETWORK_QOS_INVALID_INTERFACE_SPEED();

    String ACTION_TYPE_FAILED_QOS_OUT_OF_RANGE_VALUES();

    String ACTION_TYPE_FAILED_QOS_STORAGE_POOL_NOT_EXIST();

    String ACTION_TYPE_FAILED_QOS_STORAGE_POOL_NOT_CONSISTENT();

    String QOS_NAME_NOT_NULL();

    String QOS_NAME_INVALID();

    String QOS_NAME_TOO_LONG();

    String ACTION_TYPE_FAILED_STORAGE_QOS_ILLEGAL_VALUES();

    String ACTION_TYPE_FAILED_QOS_MISSING_VALUES();

    String ACTION_TYPE_FAILED_QOS_NEGATIVE_VALUES();

    String ACTION_TYPE_FAILED_QOS_NAME_EXIST();

    String ACTION_TYPE_FAILED_QOS_NOT_FOUND();

    String ACTION_TYPE_FAILED_PROFILE_MISSING();

    String ACTION_TYPE_FAILED_PROFILE_NOT_EXISTS();

    String ACTION_TYPE_FAILED_PROFILE_NAME_IN_USE();

    String ACTION_TYPE_FAILED_CANNOT_CHANGE_PROFILE();

    String ACTION_TYPE_FAILED_PROFILE_IN_USE();

    String ACTION_TYPE_DISK_PROFILE_EMPTY();

    String ACTION_TYPE_FAILED_DISK_PROFILE_NOT_FOUND();

    String ACTION_TYPE_DISK_PROFILE_STORAGE_DOMAIN_NOT_PROVIDED();

    String ACTION_TYPE_DISK_PROFILE_NOT_MATCH_STORAGE_DOMAIN();

    String ACTION_TYPE_DISK_PROFILE_NOT_FOUND_FOR_STORAGE_DOMAIN();

    String ACTION_TYPE_CPU_PROFILE_NOT_MATCH_CLUSTER();

    String ACTION_TYPE_CANNOT_REMOVE_LAST_CPU_PROFILE_IN_CLUSTER();

    String ACTION_TYPE_CPU_PROFILE_EMPTY();

    String ACTION_TYPE_NO_PERMISSION_TO_ASSIGN_CPU_PROFILE();

    String ACTION_TYPE_FAILED_CPU_PROFILE_NOT_FOUND();

    String ACTION_TYPE_CANNOT_REMOVE_LAST_DISK_PROFILE_IN_STORAGE_DOMAIN();

    String USER_NOT_AUTHORIZED_TO_ATTACH_DISK_PROFILE();

    String ACTION_TYPE_FAILED_REQUESTED_DISK_SIZE_IS_TOO_SMALL();

    String ACTION_TYPE_FAILED_CANNOT_RESIZE_READ_ONLY_DISK();

    String ACTION_TYPE_FAILED_CANNOT_RESIZE_DISK_SNAPSHOT();

    String VAR__ACTION__EXTEND_IMAGE_SIZE();

    String ACTION_TYPE_FAILED_CLUSTER_POLICY_PARAMETERS_INVALID();

    String ACTION_TYPE_FAILED_CLUSTER_POLICY_DUPLICATE_POLICY_UNIT();

    String ACTION_TYPE_FAILED_CLUSTER_POLICY_NAME_INUSE();

    String ACTION_TYPE_FAILED_CLUSTER_POLICY_LOCKED();

    String ACTION_TYPE_FAILED_CLUSTER_POLICY_INUSE();

    String ACTION_TYPE_FAILED_CLUSTER_POLICY_UNKNOWN_POLICY_UNIT();

    String ACTION_TYPE_FAILED_CLUSTER_POLICY_FILTER_NOT_IMPLEMENTED();

    String ACTION_TYPE_FAILED_CLUSTER_POLICY_FUNCTION_NOT_IMPLEMENTED();

    String ACTION_TYPE_FAILED_CLUSTER_POLICY_BALANCE_NOT_IMPLEMENTED();

    String ACTION_TYPE_FAILED_CLUSTER_POLICY_ONLY_ONE_FILTER_CAN_BE_FIRST();

    String ACTION_TYPE_FAILED_CLUSTER_POLICY_ONLY_ONE_FILTER_CAN_BE_LAST();

    String ACTION_TYPE_FAILED_CLUSTER_POLICY_FUNCTION_FACTOR_NEGATIVE();

    String ACTION_TYPE_FAILED_CLUSTER_POLICY_SELECTOR_NOT_IMPLEMENTED();

    String ACTION_TYPE_FAILED_CANNOT_REMOVE_POLICY_UNIT_ATTACHED_TO_CLUSTER_POLICY();

    String ACTION_TYPE_FAILED_INVALID_TIMEZONE();

    String ACTION_TYPE_EMPTY_ACTION_TYPE();

    String ERROR_GET_IMAGE_LIST();

    String ACTION_TYPE_FAILED_DISK_IS_NOT_VM_DISK();

    String ACTION_TYPE_FAILED_DISK_IS_BEING_EXPORTED();

    String ACTION_TYPE_FAILED_VM_POOL_IS_BEING_REMOVED();

    String ACTION_TYPE_FAILED_VM_POOL_IS_BEING_UPDATED();

    String ACTION_TYPE_FAILED_VM_POOL_IS_BEING_REMOVED_WITH_VM();

    String ACTION_TYPE_FAILED_VM_POOL_IS_BEING_CREATED();

    String ACTION_TYPE_FAILED_VM_IS_BEING_CREATED_AND_ATTACHED_TO_POOL();

    String ACTION_TYPE_FAILED_VM_IS_BEING_REMOVED_FROM_POOL();

    String ACTION_TYPE_FAILED_VM_COMPATIBILITY_VERSION_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_VM_USB_UNMANAGED_DEV_EXCEEDED_LIMIT();

    String ACTION_TYPE_FAILED_VM_SMARTCARD_NOT_SUPPORTED_WITHOUT_USB();

    String VAR__FILTERTYPE__INTERNAL();

    String VAR__FILTERTYPE__EXTERNAL();

    String SCHEDULING_HOST_FILTERED_REASON();

    String SCHEDULING_ALL_HOSTS_FILTERED_OUT();

    String SCHEDULING_HOST_FILTERED_REASON_WITH_DETAIL();

    String VAR__DETAIL__NETWORK_MISSING();

    String VAR__DETAIL__DISPLAY_NETWORK_MISSING();

    String VAR__DETAIL__DISPLAY_NETWORK_HAS_NO_BOOT_PROTOCOL();

    String VAR__DETAIL__NO_SUITABLE_VF();

    String CANNOT_PLUG_PASSTHROUGH_VNIC_NO_SUITABLE_VF();

    String VAR__DETAIL__LOW_CPU_LEVEL();

    String VAR__DETAIL__CPU_FLAGS_NOT_IDENTICAL();

    String VAR__DETAIL__INVALID_OS();

    String VAR__DETAIL__WRONG_OS();

    String VAR__DETAIL__OLD_OS();

    String VAR__DETAIL__CPU_OVERLOADED();

    String VAR__DETAIL__UNSUPPORTED_EMULATED_MACHINE();

    String VAR__DETAIL__UNSUPPORTED_COMPATIBILITY_VERSION();

    String ACTION_TYPE_FAILED_EMULATED_MACHINE_MAY_NOT_CONTAIN_SPECIAL_CHARS();

    String ACTION_TYPE_FAILED_CPU_NAME_MAY_NOT_CONTAIN_SPECIAL_CHARS();

    String VAR__DETAIL__AFFINITY_FAILED_POSITIVE();

    String VAR__DETAIL__AFFINITY_FAILED_NEGATIVE();

    String VAR__DETAIL__SWAP_VALUE_ILLEGAL();

    String VAR__DETAIL__NOT_ENOUGH_HUGE_PAGES();

    String VAR__DETAIL__NOT_ENOUGH_MEMORY();

    String VAR__DETAIL__NUMA_NOT_SUPPORTED();

    String VAR__DETAIL__NOT_MEMORY_PINNED_NUMA();

    String VAR__DETAIL__NOT_ENOUGH_CORES();

    String VAR__DETAIL__VM_PINNING_PCPU_DOES_NOT_EXIST();

    String VAR__DETAIL__NUMA_PINNING_FAILED();

    String VAR__DETAIL__CLUSTER_IN_MAINTENANCE();

    String VAR__DETAIL__NOT_PINNED_TO_HOST();

    String VM_NUMA_NODE_PREFERRED_NOT_PINNED_TO_SINGLE_NODE();

    String VM_NUMA_NODE_MORE_NODES_THAN_CPUS();

    String VM_NUMA_PINNED_VDS_NOT_EXIST();

    String VM_NUMA_NODE_HOST_NODE_INVALID_INDEX();

    String VM_NUMA_PINNED_VDS_NODE_EMPTY();

    String VM_NUMA_NODE_PINNED_INDEX_ERROR();

    String VM_NUMA_NODE_MEMORY_ERROR();

    String VM_NUMA_NODE_TOTAL_MEMORY_ERROR();

    String VM_NUMA_NODE_NOT_MULTIPLE_OF_HUGEPAGE();

    String HOST_NUMA_NOT_SUPPORTED();

    String VM_NUMA_NODE_INDEX_DUPLICATE();

    String VM_NUMA_NODE_NON_CONTINUOUS_INDEX();

    String VM_NUMA_NODE_DUPLICATE_CPU_IDS();

    String VM_NUMA_NODE_INVALID_CPU_ID();

    String VM_NVDIMM_NUMA_UNAVAILABLE();

    String VAR__DETAIL__NOT_HE_HOST();

    String VAR__DETAIL__HE_HOST_NOT_POSITIVE_SCORE();

    String VAR__DETAIL__HE_HOST_LOW_SCORE();

    String VAR__DETAIL__NOT_ENOUGH_HE_SPARES();

    String VAR__DETAIL__SAME_HOST();

    String VAR__DETAIL__TSC_FREQ_MISMATCH();

    String VAR__DETAIL__HOSTDEV_DISABLED();

    String VAR__DETAIL__HOST_DEVICE_UNAVAILABLE();

    String VAR__DETAIL__HOST_MDEV_DEVICE_MISSING();

    String VAR__DETAIL__HOST_MDEV_DEVICE_UNAVAILABLE();

    String VAR__DETAIL__WRONG_HOST_FOR_REQUESTED_HOST_DEVICES();

    String SCHEDULING_NO_HOSTS();

    String POWER_MANAGEMENT_ACTION_ON_ENTITY_ALREADY_IN_PROGRESS();

    String AFFINITY_GROUP_NAME_TOO_LONG();

    String AFFINITY_GROUP_NAME_INVALID();

    String AFFINITY_GROUP_DESCRIPTION_INVALID();

    String ACTION_TYPE_FAILED_AFFINITY_GROUP_INVALID_CLUSTER_ID();

    String ACTION_TYPE_FAILED_INVALID_CLUSTER_FOR_AFFINITY_GROUP();

    String ACTION_TYPE_FAILED_INVALID_ENTITY_FOR_AFFINITY_GROUP();

    String ACTION_TYPE_FAILED_INVALID_LABEL_FOR_AFFINITY_GROUP();

    String ACTION_TYPE_FAILED_ENTITY_NOT_IN_AFFINITY_GROUP_CLUSTER();

    String ACTION_TYPE_FAILED_DUPLICATE_ENTITY_IN_AFFINITY_GROUP();

    String ACTION_TYPE_FAILED_DUPLICATE_LABEL_IN_AFFINITY_GROUP();

    String ACTION_TYPE_FAILED_INVALID_AFFINITY_GROUP_ID();

    String ACTION_TYPE_FAILED_CANNOT_CHANGE_CLUSTER_ID();

    String ACTION_TYPE_FAILED_AFFINITY_GROUP_NAME_EXISTS();

    String ACTION_TYPE_FAILED_POSITIVE_AFFINITY_GROUP();

    String ACTION_TYPE_FAILED_NEGATIVE_AFFINITY_GROUP();

    String ACTION_TYPE_FAILED_MIX_POSITIVE_NEGATIVE_AFFINITY_GROUP();

    String ACTION_TYPE_FAILED_AFFINITY_RULES_COLLISION();

    String ACTION_TYPE_FAILED_AFFINITY_HOSTS_RULES_COLLISION();

    String AFFINITY_GROUPS_LIST();

    String HOSTS_LIST();

    String VMS_LIST();

    String VALIDATION_ISCSI_BOND_NAME_MAX();

    String VALIDATION_ISCSI_BOND_NAME_NOT_NULL();

    String VALIDATION_ISCSI_BOND_DESCRIPTION_MAX();

    String VALIDATION_ISCSI_BOND_NAME_INVALID_CHARACTER();

    String ISCSI_BOND_WITH_SAME_NAME_EXIST_IN_DATA_CENTER();

    String ISCSI_BOND_NOT_EXIST();

    String ACTION_TYPE_FAILED_INVALID_SERIAL_NUMBER();

    String ACTION_TYPE_FAILED_STORAGE_CONNECTIONS_CANNOT_BE_ADDED_TO_ISCSI_BOND();

    String ACTION_TYPE_FAILED_ISCSI_BOND_NETWORK_CANNOT_BE_REQUIRED();

    String ACTION_TYPE_FAILED_INTERFACE_DOES_NOT_SUPPORT_READ_ONLY_ATTR();

    String ACTION_TYPE_FAILED_RNG_NOT_FOUND();

    String ACTION_TYPE_FAILED_RNG_ALREADY_EXISTS();

    String ACTION_TYPE_FAILED_RNG_SOURCE_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_QEMU_UNSUPPORTED_OPERATION();

    String ACTION_TYPE_FAILED_MEMORY_EXCEEDS_SUPPORTED_LIMIT();

    String KDUMP_DETECTION_NOT_ENABLED_FOR_VDS();

    String KDUMP_DETECTION_NOT_CONFIGURED_ON_VDS();

    String VDS_CLUSTER_ON_DIFFERENT_STORAGE_POOL();

    String PLUGGED_UNLINKED_VM_INTERFACE_WITH_EXTERNAL_NETWORK_IS_NOT_SUPPORTED();

    String SOUND_DEVICE_REQUESTED_ON_NOT_SUPPORTED_ARCH();

    String USE_HOST_CPU_REQUESTED_ON_UNSUPPORTED_ARCH();

    String CPU_TYPE_UNSUPPORTED_FOR_THE_GUEST_OS();

    String CPU_TYPE_UNKNOWN();

    String MEMORY_SIZE_NOT_MULTIPLE_OF_256_ON_PPC();

    String ACTION_TYPE_FAILED_NOT_PLUGGED_MEMORY_ON_ARCH_MUST_BE_DIVIDABLE_BY();

    String ACTION_TYPE_FAILED_NOT_SUPPORTED_FOR_EXTERNAL_NETWORK();

    String ACTION_TYPE_FAILED_CANNOT_REMOVE_PHYSICAL_NETWORK_LINKED_TO_EXTERNAL_NETWORK();

    String ACTION_TYPE_FAILED_DATA_CENTER_ID_CANNOT_BE_CHANGED();

    String ACTION_TYPE_FAILED_NETWORK_PORT_ISOLATION_CANNOT_BE_CHANGED();

    String CIDR_NOT_NETWORK_ADDRESS();

    String BAD_CIDR_FORMAT();

    String ACTION_TYPE_FAILED_DEVICE_MUST_BE_SPECIFIED();

    String ACTION_TYPE_FAILED_GRAPHIC_TYPE_MUST_BE_SPECIFIED();

    String ACTION_TYPE_REMOVE_GRAPHICS_DEV_INVALID_PARAMS();

    String ACTION_TYPE_FAILED_ONLY_ONE_DEVICE_WITH_THIS_GRAPHICS_ALLOWED();

    String ACTION_TYPE_FAILED_PROVIDER_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_CINDER();

    String CANNOT_ADD_CINDER_DISK_VOLUME_LIMIT_EXCEEDED();

    String CANNOT_ADD_CINDER_DISK_SNAPSHOT_LIMIT_EXCEEDED();

    String CINDER_DISK_ALREADY_REGISTERED();

    String NO_FOREMAN_PROVIDER_FOR_ENGINE();

    String NO_FOREMAN_PROVIDER_FOR_VM();

    String NO_FOREMAN_PROVIDER_FOR_HOST();

    String ACTION_TYPE_FAILED_VM_NOT_PINNED_TO_HOST();

    String ACTION_TYPE_FAILED_VM_NOT_PINNED_TO_AT_LEAST_ONE_HOST();

    String ACTION_TYPE_FAILED_VM_PINNED_TO_MULTIPLE_HOSTS();

    String ACTION_TYPE_FAILED_HOST_DEVICE_NOT_FOUND();

    String ACTION_TYPE_FAILED_HOST_DEVICE_NOT_AVAILABLE();

    String ACTION_TYPE_FAILED_HOST_DEVICE_ALREADY_IN_USE();

    String ACTION_TYPE_FAILED_VM_MEMORY_DEVICE_DOESNT_EXIST();

    String ACTION_TYPE_FAILED_REQUIRED_SPEC_PARAM_IS_MISSING();

    String ACTION_TYPE_FAILED_MEMORY_DEVICE_IS_BEING_HOT_UNPLUGGED();

    String ACTION_TYPE_FAILED_MEMORY_HOT_UNPLUG_NOT_SUPPORTED_FOR_COMPAT_VERSION_AND_ARCH();

    String ACTION_TYPE_FAILED_MEMORY_HOT_SET_NOT_SUPPORTED_FOR_HUGE_PAGES();

    String ACTION_TYPE_FAILED_HOT_PLUGGED_MEMORY_MUST_BE_DIVIDABLE_BY();

    String ACTION_TYPE_CANNOT_CHANGE_INITIAL_RUN_DATA();

    String CLUSTER_BIOS_TYPE_NOT_SET();

    String NON_DEFAULT_BIOS_TYPE_FOR_X86_ONLY();

    String Q35_NOT_SUPPORTED_BY_GUEST_OS();

    String SECURE_BOOT_NOT_SUPPORTED_BY_GUEST_OS();

    String VM_ICON_DATAURL_MALFORMED();

    String PROVIDED_VM_ICON_OF_UNKNOWN_TYPE();

    String PROVIDED_VM_ICON_CANT_BE_READ();

    String VM_ICON_MIME_TYPE_DOESNT_MATCH_IMAGE_DATA();

    String PROVIDED_VM_ICON_HAS_INVALID_DIMENSIONS();

    String DATA_SIZE_OF_PROVIDED_VM_ICON_TOO_LARGE();

    String VM_ICON_BASE64_PART_MALFORMED();

    String ICON_OF_PROVIDED_ID_DOES_NOT_EXIST();

    String CINDER_VOLUME_TYPE_NOT_EXISTS();

    String ERROR_CANNOT_DETACH_CINDER_PROVIDER_WITH_IMAGES();

    String BLANK_TEMPLATE_CANT_HAVE_SUBTEMPLATES();

    String LIBVIRT_SECRET_UUID_CANNOT_BE_EMPTY();

    String LIBVIRT_SECRET_VALUE_CANNOT_BE_EMPTY();

    String LIBVIRT_SECRET_VALUE_ILLEGAL_FORMAT();

    String LIBVIRT_SECRET_UUID_ALREADY_EXISTS();

    String LIBVIRT_SECRET_UUID_NOT_EXISTS();

    String FAILED_TO_CONNECT_MANAGED_BLOCK_DOMAIN();

    String ACTION_TYPE_FAILED_NUM_OF_IOTHREADS_INCORRECT();

    String CLUSTER_WARN_HOST_DUE_TO_UNSUPPORTED_HWRNG_SOURCE();

    String CLUSTER_WARN_HOST_DUE_TO_UNSUPPORTED_MACHINE_TYPE();

    String CLUSTER_WARN_VM_DUE_TO_DECREASED_CLUSTER_CPU_LEVEL();

    String CLUSTER_WARN_VM_DUE_TO_EMULATED_MACHINE_CHANGE_ON_WINDOWS();

    String CLUSTER_WARN_VM_DUE_TO_EMULATED_MACHINE_CHANGE_ON_WINDOWS_WITH_SECONDARY_DISK();

    String ACTION_TYPE_FAIL_VDS_CANNOT_CONNECT_TO_GLUSTERFS();

    String ACTION_TYPE_FAILED_HOST_CANNOT_BE_PROXY_FOR_IMPORT_VM();

    String ACTION_TYPE_FAILED_NO_HOST_CAN_BE_PROXY_FOR_IMPORT_VM();

    String INVALID_BOND_MODE_FOR_BOND_WITH_VM_NETWORK();

    String INVALID_BOND_MODE_FOR_BOND_WITH_LABELED_VM_NETWORK();

    String NETWORK_ATTACHMENT_MISSING_IP_CONFIGURATION();

    String NETWORK_ATTACHMENT_IP_CONFIGURATION_MISSING_BOOT_PROTOCOL();

    String NETWORK_ATTACHMENT_IP_CONFIGURATION_INCOMPATIBLE_BOOT_PROTOCOL_AND_IP_ADDRESS_DETAILS();

    String NETWORK_ATTACHMENT_IP_CONFIGURATION_STATIC_BOOT_PROTOCOL_MISSING_IP_ADDRESS_DETAILS();

    String NETWORK_ATTACHMENT_IP_CONFIGURATION_STATIC_BOOT_PROTOCOL_IPV6_GATEWAY_ON_NON_DEFAULT_ROUTE_ROLE();

    String SETTING_VM_TICKET_FAILED();

    String ACTION_TYPE_FAILED_VM_HAS_ATTACHED_PCI_HOST_DEVICES();

    String ACTION_TYPE_FAILED_VM_HAS_ATTACHED_SCSI_HOST_DEVICES();

    String ACTION_TYPE_FAILED_VM_HAS_ATTACHED_NVDIMM_DEVICES();

    String ACTION_TYPE_FAILED_VM_HAS_TPM();

    String ACTION_TYPE_FAILED_VM_USES_MDEV_TYPE_HOOK();

    String ACTION_TYPE_FAILED_MISSING_HOST_BLOCK_DEVICE_PATH();

    String ACTION_TYPE_FAILED_HOST_NETWORK_LABEL_ON_UNMANAGED_NETWORK();

    String ACTION_TYPE_FAILED_HOST_NETWORK_ATTACHEMENT_ON_UNMANAGED_NETWORK();

    String NETWORK_INTERFACE_WITH_UNMANAGED_NETWORK_CANNOT_BE_SLAVE();

    String REMOVED_UNMANAGED_NETWORK_IS_A_CLUSTER_NETWORK();

    String REMOVED_UNMANAGED_NETWORK_DOES_NOT_EXISIT_ON_HOST();

    String ACTION_TYPE_FAILED_EDITING_HOSTED_ENGINE_IS_DISABLED();

    String ACTION_TYPE_FAILED_EXTERNAL_PROVIDER_IS_READ_ONLY();

    String AFFINITY_LABEL_NOT_EXISTS();

    String AFFINITY_LABEL_BAD_NAME();

    String AFFINITY_LABEL_NAME_SIZE_INVALID();

    String AFFINITY_LABEL_NOT_FROM_SELECTED_CLUSTER();

    String AFFINITY_LABEL_NOT_EMPTY();

    String AFFINITY_LABEL_ID_ALREADY_EXISTS();

    String AFFINITY_LABEL_NAME_ALREADY_EXISTS();

    String AFFINITY_LABEL_READ_ONLY();

    String ACTION_TYPE_FAILED_CLUSTER_IS_BEING_UPDATED();

    String ACTION_TYPE_FAILED_ATTRIBUTE_PATH();

    String ACTION_TYPE_FAILED_PROVIDER_NO_PLUGIN_TYPE();

    String ACTION_TYPE_FAILED_PROVIDER_NO_USER();

    String ACTION_TYPE_FAILED_PROVIDER_NO_PASSWORD();

    String ACTION_TYPE_FAILED_PROVIDER_NO_AUTH_URL();

    String ACTION_TYPE_FAILED_PROVIDER_INVALID_AUTH_URL();

    String ACTION_TYPE_FAILED_PROVIDER_INVALID_PROMETHEUS_URL();

    String ACTION_TYPE_FAILED_PROVIDER_PASSWORD_TOO_LONG();

    String ACTION_TYPE_FAILED_PROVIDER_FAILED_FETCH_TEMPLATES();

    String ACTION_TYPE_FAILED_PROVIDER_TEMPLATES_NOT_FOUND();

    String ACTION_TYPE_FAILED_PROVIDER_KUBEVIRT_NOT_FOUND();

    String ACTION_TYPE_FAILED_PROVIDER_FAILED_FETCH_VERSIONS();

    String ACTION_TYPE_FAILED_PROVIDER_NO_TENANT_OR_USER_DOMAIN();

    String ACTION_TYPE_FAILED_IMAGE_NOT_SPECIFIED_FOR_DOWNLOAD();

    String ACTION_TYPE_FAILED_CANNOT_TRANSFER_IMAGE_STATUS_MISSING_PARAM();

    String ACTION_TYPE_FAILED_CANNOT_RESUME_IMAGE_TRANSFER();

    String ACTION_TYPE_FAILED_CANNOT_PAUSE_IMAGE_DOWNLOAD();

    String NETWORK_OUT_OF_RANGE_MACS();

    String ERROR_STORAGE_DOMAIN_SYNC_EXISTS();

    String ACTION_TYPE_FAILED_GEOREP_SESSION_USED_IN_STORAGE_SYNC();

    String SCHEDULE_HOUR_OUT_OF_RANGE();

    String SCHEDULE_MINS_OUT_OF_RANGE();

    String STORAGE_DOMAIN_SYNC_SCHEDULING_IN_PROGRESS();

    String VALIDATION_INVALID_SCHEDULE();

    String ACTION_TYPE_FAILED_DEFAULT_ROUTE_NETWORK_CANNOT_BE_EXTERNAL();

    String CLUSTER_CANNOT_UPDATE_CLUSTER_FAILED_TO_UPDATE_VMS();

    String BAD_IPV4_OR_IPV6_ADDRESS_FORMAT();

    String ACTION_TYPE_FAILED_INVALID_VM_LEASE();

    String ACTION_TYPE_FAILED_VM_LEASE_IS_NOT_READY_FOR_HOST();

    String ACTION_TYPE_FAILED_INVALID_VM_LEASE_STORAGE_DOMAIN_STATUS();

    String ACTION_TYPE_FAILED_CANNOT_MIGRATE_MACS_DUE_TO_DUPLICATES();

    String ACTION_TYPE_FAILED_CANNOT_ADD_IFACE_DUE_TO_MAC_DUPLICATES();

    String VALIDATION_CLOUD_INIT_START_ON_BOOT_INVALID();

    String VALIDATION_CLOUD_INIT_IPV6_AUTOCONF_UNSUPPORTED();

    String VALIDATION_CLOUD_INIT_STATIC_IPV4_ADDRESS_MISSING();

    String VALIDATION_CLOUD_INIT_STATIC_IPV6_ADDRESS_MISSING();

    String ACTION_TYPE_FAILED_INVALID_OVA_DESTINATION_FOLDER();

    String CANNOT_MOVE_DISK_SNAPSHOTS();

    String CANNOT_MOVE_DISK_TEMPLATE();

    String CANNOT_LIVE_MIGRATE_VM_SHOULD_BE_IN_PAUSED_OR_UP_STATUS();

    String ACTION_TYPE_FAILED_MAC_POOL_CONTAINS_DUPLICATES();

    String VAR__ACTION__REPLACE_GLUSTER_BRICK();

    String VAR__ACTION__RESET_GLUSTER_BRICK();

    String ACTION_TYPE_GLUSTER_VOLUME_PRESENT_IN_STORAGE_DOMAIN();

    String ACTION_TYPE_FAILED_CANNOT_ACTIVATE_MANAGED_BLOCK_STORAGE_DOMAIN();

    String ACTION_TYPE_FAILED_CINDERLIB_DATA_BASE_REQUIRED();

    String CPU_HOTPLUG_TOPOLOGY_INVALID();

    String ACTION_TYPE_FAILED_VM_IS_DURING_BACKUP();

    String ACTION_TYPE_FAILED_INCREMENTAL_BACKUP_NOT_SUPPORTED_FOR_RAW_DISK();

    String ACTION_TYPE_FAILED_INCREMENTAL_BACKUP_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_MIXED_INCREMENTAL_AND_FULL_BACKUP_NOT_SUPPORTED();

    String ACTION_TYPE_FAILED_CHECKPOINT_NOT_EXIST();

    String ACTION_TYPE_FAILED_CHECKPOINT_INVALID();

    String ACTION_TYPE_FAILED_MAC_POOL_CONTAINS_OVERLAPPING_RANGES();

    String ACTION_TYPE_FAILED_MAC_POOL_OVERLAPS_WITH_OTHER_POOLS();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_PERFORMANCE_O_DIRECT_DISABLE();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_SHARDING_DISABLE();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_REMOTE_DIO_ON();

    String CLUSTER_CANNOT_DISABLE_GLUSTER_WHEN_CLUSTER_CONTAINS_VOLUMES();

    String ACTION_TYPE_CANNOT_SET_MANUAL_PINNING();

    String ACTION_TYPE_CANNOT_RESIZE_AND_PIN_SINGLE_CORE();

    String ACTION_TYPE_CANNOT_RESIZE_AND_PIN_AND_NUMA_SET();

    String ACTION_TYPE_FAILED_MASTER_ROLE_IS_BEING_SWITCHED();

    String VAR__TYPE__STORAGE__DOMAIN__SWITCH_MASTER();

    String ACTION_TYPE_FAILED_STORAGE_DOMAIN_ALREADY_MASTER();

    String ACTION_TYPE_FAILED_STORAGE_POOL_HAS_RUNNING_TASKS();

    String ACTION_TYPE_FAILED_USER_PROFILE_MULTIPLE_SSH_KEYS();

    String ACTION_TYPE_FAILED_USER_PROFILE_PROPERTY_NOT_EXISTS();

    String ACTION_TYPE_FAILED_USER_PROFILE_PROPERTY_ALREADY_EXISTS();

    String ACTION_TYPE_FAILED_USER_PROFILE_PROPERTY_ALREADY_EXIST_WITH_DIFFERENT_NAME();

    String ACTION_TYPE_FAILED_USER_PROFILE_PROPERTY_ALREADY_EXIST_WITH_DIFFERENT_TYPE();

    String ACTION_TYPE_FAILED_GLUSTER_STORAGE_CONNECTION_UNSUPPORTED_STORAGE_TYPE();

}

