#!/bin/sh

#
# Copyright oVirt Authors
# SPDX-License-Identifier: Apache-2.0
#

ansiblescriptdir="$(readlink -f "$1")"
setuplib=$(readlink -f $(dirname ${ansiblescriptdir})/setup)
export PYTHONPATH="$setuplib:${PYTHONPATH}"
exec "${ansiblescriptdir}"/roles/ovirt-to-vdsm-network/files/ovirt-to-vdsm-network.py "$2" "$3"
