.\" engine-log-collector - oVirt Engine Tool for Collecting Data
.TH "engine-log-collector" "8" "" "Keith Robertson" ""
.SH "NAME"
engine\-log\-collector \- oVirt Enterprise Virtualization Engine Manager (RHEV\-M) Log Collector

.SH "SYNOPSIS"
\fBengine\-log\-collector\fP [options] list

.PP

\fBengine\-log\-collector\fP [options] collect

.SH "DESCRIPTION"
.PP

The \fBengine\-log\-collector\fP command gathers data from many different components (logs, databases, and environmental information) associated with an instance of a oVirt Enterprise Virtualization Engine Manager (RHEV\-M). The tool is intended to be run from the Linux system on which the RHEV\-M is running as the root user.\&

.PP
The \fBengine\-log\-collector\fP will, by default, attempt to interact with the RHEV\-M REST API. This command typically gets the RHEV\-M's hostname and port number (engine=) and user name (user=) from the \fB/etc/engine/logcollector.conf\fP file. Alternatively, you can provide the user name and password from the command line. The user name and password are authenticated by the authentication service associated with the RHEV\-M.  Currently, a special local account (admin), Red Hat IPA server, and Microsoft Active Directory server is supported for this task.
.PP

Central to the \fBengine\-log\-collector\fP command is a series of plug\-ins to the \fBsosreport\fP(1) application. These plug\-ins and other components gather information about hypervisors managed by the RHEV\-M into a single archive (a sort of \fBsosreport\fP(1) of sosreports).

.PP

The \fBlist\fP option lists hypervisors controlled by the RHEV\-M, while \fBcollect\fP (default) actually runs the collection. The result of running \fBengine\-log\-collector\fP is a compressed archive that contains logs and other information from some or all of the following:

.\' Describe engine\-slimmed

.IP "\fB* Hypervisor Log Collection\fP"

Logs from all RHEV\-H and RHEL\-H hypervisors managed by the RHEV\-M are gathered by default. The \-\-no\-hypervisors option lets you choose to not collect any hypervisor information. Other options let you limit log collection to specific clusters, data centers or hosts. Some options require that the log collector communicate with the RHEV\-M RESTful API. The communication is needed to retrieve the list of hosts in a cluster or datacenter, and is transparent to the user.\&

.IP "\fB* PostgreSQL Log Collection\fP"

Log collector always tries to get some PostgreSQL information. Using a PostgreSQL \fBsosreport\fP(1) plug\-in, log collector gathers all logs in POSTGRE_HOME and optionally dumps a designated database if a username and password are supplied. PostgreSQL reports are prefixed with postgre\-. For example:\&

postgresql\-sosreport\-rhel6\-20110613221045\-f914.ta r.xz.\&

.IP "\fB* JBoss Log Collection\fP"

The log collector always attempt to gather some information from JBoss. The JBoss \fBsosreport\fP(1) plug\-in is extensive and it will capture logs, configuration information, datasource files and other information by default. If the user supplies a JMX console administrator user ID and password even more information will be captured (e.g. memory and thread information). The RHEV\-M installer does not configure a JMX console administrator by default. Follow the instructions in the JBoss manuals to securely enable the JMX console administrator to collect this useful information, otherwise press Control\-D to skip the collection of this information when prompted.\&

.IP "\fB* Clock Skew\fP"

To deal with cases where hypervisors are not syncronized with NTP, a file called time_diff.txt is created to list the clock skew of each hypervisor relative to the RHEV\-M.  This file is included in the report whenever you elect to collect information from a hypervisor.

.PP

.SH "GENERAL OPTIONS"
The following are general options you can use with this command:\&

.IP "\fB\-\-version\fP"

Show the program's version number and exit.\&

.IP "\fB\-h, \-\-help\fP"

Show the help message and exit.\&

.IP "\fB\-\-local\-tmp=PATH\fP"

Local directory where reports are copied (default=/tmp/logcollector).\&

.IP "\fB\-\-config\-file=PATH\fP"

Path to the configuration file (default=/etc/engine/logcollector.conf).\&

.IP "\fB\-\-ticket\-number=TICKET\fP"

Ticket number (also called a case number) to pass with the \fBsosreport\fP(1).\&

.IP "\fB\-\-upload=FTP_SERVER\fP"

Upload the report produced by this command to Red Hat (use exclusively if advised from a Red Hat support representative). Replace FTP_SERVER with the location of the FTP server.\&

.IP "\fB\-\-quiet\fP"

Reduce the amount of console output (default=False).\&

.IP "\fB\-\-log\-file=PATH\fP"

Path to \fBengine\-log\-collector\fP log file (default=/var/log/engine\-log\-collector.log).\&

.IP "\fB\-v, \-\-verbose\fP"

Display verbose output.\&

.SH "oVirt Engine CONFIGURATION OPTIONS"
The options in the RHEV\-M configuration group can be used to filter log collection from one or more RHEV\-H or RHEL\-H systems. If the \-\-no\-hypervisors option is specified, data is not collected from any RHEV\-H. Wild card globbing (*, ?, []) can be used to match names.\&

.IP "\fB\-\-no\-hypervisors\fP"

Skip all collection from hypervisors (default=False).\&

.IP "\fB\-u user@engine.example.com, \-\-user=user@engine.example.com\fP"

Indicates the user name to use with the REST API. This should be in UPN format.\&

.IP "\fB\-r engine.example.com, \-\-engine=engine.example.com\fP"

Hostname or IP address of the RHEV\-M (default=localhost:8443).\&

.IP "\fB\-c CLUSTER, \-\-cluster=CLUSTER\fP"

Replace CLUSTER with a pattern or comma\-separated list of patterns, to filter the host list by cluster name (default=None).\&

.IP "\fB\-d DATACENTER, \-\-data\-center=DATACENTER\fP"

Replace DATACENTER with a pattern, or comma separated list of patterns, to filter the host list by data center name (default=None).\&

.IP "\fB\-H HOST_LIST, \-\-hosts=HOST_LIST\fP"

Replace HOST_LIST with a pattern, or comma separated list of hostnames, hostname patterns, FQDNs, FQDN patterns, IP addresses, or IP address patterns from which the log collector should collect RHEV\-H logs (default=None).\&

.SH "SOSREPORT OPTIONS"
The JBoss \fBsosreport\fP(1) plug\-in is always executed. To activate data collection from JBoss's JMX console java\-home, jboss\-user, and jboss\-pass must also be specified. If no jboss\-pass is supplied in the configuration file then it will be asked for prior to collection time.

.IP "\fB\-\-jboss\-home=/path/to/jbossas\fP"

JBoss's installation dir (default=/var/lib/jbossas).\&

.IP "\fB\-\-java\-home=/path/to/java\fP"

Java's installation dir (default=/usr/lib/jvm/java).\&

.IP "\fB\-\-jboss\-profile=PROFILE1,PROFILE2\fP"

Comma separated list of server profiles to limit

collection (default=engine\-slimmed).\&

.IP "\fB\-\-jboss\-user=admin\fP"

JBoss JMX username (default=admin).\&

.IP "\fB\-\-jboss\-logsize=15\fP"

Maximum size (MiB) to collect per log file (default=15).\&

.IP "\fB\-\-jboss\-stdjar=on or off\fP"

Collect jar statistics for JBoss standard jars (default=on).\&

.IP "\fB\-\-jboss\-servjar=on or off\fP"

Collect jar statistics from any server configuration

dirs (default=on).\&

.IP "\fB\-\-jboss\-twiddle=on or off\fP"

Collect JBoss twiddle data (default=on).\&

.IP "\fB\-\-jboss\-appxml=APP, APP2\fP"

Comma separated list of application's whose XML descriptors you want (default=all).\&

.SH "SSH CONFIGURATION"
The options in the SSH configuration group can be used to specify the maximum number of concurrent SSH connections to RHEV\-H(s) for log collection, the SSH port, and a identity file to be used.\&

.IP "\fB\-\-ssh\-port=PORT\fP"

The port used for ssh and scp communications.\&

.IP "\fB\-k KEYFILE, \-\-key\-file=KEYFILE\fP"

The identity file (private key) to be used for accessing the RHEV\-H systems (default=/etc/pki/engine/keys/engine_id_rsa). If an identity file is not supplied the program will prompt for a password. It is strongly recommended to use key\-based authentication with SSH because the program may make multiple SSH connections resulting in multiple requests for the SSH password.\&

.IP "\fB\-\-max\-connections=MAX_CONNECTIONS\fP"

Maximum concurrent connections for fetching RHEV\-H logs (default=10).\&

.SH "POSTGRESQL DATABASE CONFIGURATION"
The log collector will connect to the RHEV\-M PostgreSQL database and dump the data for inclusion in the log report, unless \-\-no\-postgresql is specified. The PostgreSQL user ID and database name can be specified if they are different from the defaults. If the PostgreSQL database is not on the localhost, set pg\-dbhost, provide a pg\-ssh\-user, and optionally supply pg\-host\-key and the log collector will gather remote PostgreSQL logs. The PostgreSQL \fBsosreport\fP(1) plug\-in must be installed on pg\-dbhost for successful remote log collection.\&

.IP "\fB\-\-no\-postgresql\fP"

This option causes the tool to skip the postgresql collection (default=false).\&

.IP "\fB\-\-pg\-user=postgres\fP"

PostgreSQL database user name (default=postgres).\&

.IP "\fB\-\-pg\-dbname=engine\fP"

PostgreSQL database name (default=engine).\&

.IP "\fB\-\-pg\-dbhost=localhost\fP"

PostgreSQL database hostname or IP address (default=localhost).\&

.IP "\fB\-\-pg\-ssh\-user=root\fP"

The SSH user that will be used to connect to the server upon which the remote PostgreSQL database lives (default=root).\&

.IP "\fB\-\-pg\-host\-key=none\fP"

The identity file (private key) to be used for accessing the host upon which the PostgreSQL database lives (default=not needed if using localhost).\&

.SH "EXAMPLES"
Before running \fBengine\-log\-collector\fP to collect data, you should run one or more list commands, to hone in on the data you want. Here's an example of the the output using a list option to see all hosts managed by the RHEV\-M:

.PP

# \fBengine\-log\-collector\fP list

.br

Please provide the password for engine (CTRL+D to abort):  ********
.br
Host list (datacenter=None, cluster=None, host=None):
.br
Data Center          | Cluster              | Hostname/IP Address
.br
Legacy               | LegacyCluster        | 192.168.122.11
.br
Legacy               | NewCluster           | 192.168.125.42

Use the \-\-hosts= option to limit output to a particular host or group of hosts (using wildcards, as needed).

.PP

# \fBengine\-log\-collector\fP list \-\-hosts=*.11

.br

Please provide the password for engine (CTRL+D to abort):
.br
Host list (datacenter=None, cluster=None, host=set(['*.11'])):
.br
Data Center          | Cluster              | Hostname/IP Address
.br
Legacy               | LegacyCluster        | 192.168.122.11

.PP

Instead of having log collector collect logs from all hypervisors managed by the RHEV\-M (default), you can use the same options you used with \fBlist\fP to limit data collection to specific hosts (or datacenters or clusters). Here, all hosts with IP addresses ending in .11 are matched:\&

.PP

# \fBengine\-log\-collector\fP collect \-\-hosts=*.11

.br

Please provide the password for engine (CTRL+D to abort):
.br
About to collect information from 1 hypervisors. Continue? (Y/n): \fBY\fP
.br
INFO: Gathering information from selected hypervisors...
.br
INFO: Collecting information from 192.168.122.11
.br
.PP

To gather data, from multiple hosts, provide a comma\-separated list of addresses or host names. The following example gathers data from all hosts ending in .11 or .15:\&

.PP

# \fBengine\-log\-collector\fP collect \-\-hosts=*.11,*.15

.PP

Use the cluster option to gather data based on cluster name. Here, information on all hosts with IP addresses ending in .11 or .15 are matched from any cluster beginning with the letter L (using * as a wild card):\&

.PP

# \fBengine\-log\-collector\fP collect \-\-cluster=L* \-\-hosts=*.11,*.15

.PP

Likewise, you can gather data based on data center. Here, all hosts from the example.com domain are matched from any data center beginning with the letter L (using * as a wild card):\&

.PP

# \fBengine\-log\-collector\fP collect \-\-data\-center=L* \-\-hosts=*.example.com

.br

.SH "CONFIGURATION FILE"
To get configuration information, \fBengine\-log\-collector\fP refers to the \fB/etc/engine/logcollector.conf\fP configuration file. To set defaults for any of the options described in this man page, uncomment the settings you want in this file. Here examples of a few lines from that file:

.PP

[LogCollector]

.br

###  RHEV\-M Configuration:

.br

## username to use with the REST API

.br

user=joe@example.com

.br

# password to use with the REST API

.br

passwd=L1ghtNingFst1!

.br

## hostname or IP address of the RHEV\-M

.br

engine=myengine.example.com:8443

.SH "ERRORS"
* If JBoss is down for the RHEV\-M, it limits the scope of what you can collect.\&

.br

.SH "RETURN VALUES"
.IP "\fB0\fP"

The program ran to completion with no errors.\&

.IP "\fB1\fP"

The program encountered a critical failure and stopped.\&

.IP "\fB2\fP"

The program encountered a problem gathering data but was able to continue.\&

.PP

.SH "FILES"
.nf

/etc/engine/logcollector.conf

/tmp/logcollector

/var/log/engine\-log\-collector.log

/var/lib/jbossas

/usr/lib/jvm/java

/etc/pki/engine/keys/engine_id_rsa

.fi

.SH "SEE ALSO"
\fBsosreport\fP(1)

.SH "AUTHOR"
.nf

Keith Robertson

