---
# Set up the volume management
- name: Fetch the directory and volume details
  block:
    - name: Get the list of volumes on the machine
      ansible.builtin.command:
        argv:
          - ls
          - "{{ glusterd_libdir }}/vols"
      register: dir_list

    - name: Setting Facts for Volume
      ansible.builtin.set_fact:
        volumes: "{{ dir_list.stdout.split() }}"

    # Find the list of bricks on the machine
    - name: Get the list of bricks corresponding to volume
      ansible.builtin.shell: >
        gluster vol info {{ item }} |
        grep {{ gluster_maintenance_old_node }} |
        cut -d' ' -f2 |
        awk -F: '{ print $2 }'
      with_items: "{{ volumes }}"
      register: brick_list
  delegate_to: "{{ gluster_cluster_node }}"
  connection: ssh

- name: Run replace-brick commit on the brick
  connection: ssh
  ansible.builtin.shell: >
    [ ! -d {{ item.1 }} ] && gluster volume replace-brick {{ item.0.item }}
    {{ gluster_old_node }}:{{ item.1 }}
    {{ gluster_new_node }}:{{ item.1 }}
    commit force
  register: ret
  failed_when: ret.rc >= 2
  with_subelements:
    - "{{ brick_list.results }}"
    - stdout_lines
  delegate_to: "{{ gluster_new_node }}"
