package org.ovirt.engine.ui.uicommonweb.models;

/**
 * Enumeration of all available tab names.
 */
public enum TabName {
    GENERAL_TAB,
    CONSOLE_TAB,
    MIGRATION_TAB,
    OPTIMIZATION_TAB,
    CLUSTER_POLICY_TAB,
    CLUSTERS_TAB,
    PROFILES_TAB,
    SUBNET_TAB,
    POWER_MANAGEMENT_TAB,
    SPM_TAB,
    BOOT_OPTIONS_TAB,
    CUSTOM_PROPERTIES_TAB,
    DNS_CONFIGURATION_TAB,
    HIGH_AVAILABILITY_TAB,
    HOST_TAB,
    INITIAL_RUN_TAB,
    POOL_TAB,
    RESOURCE_ALLOCATION_TAB,
    SYSTEM_TAB,
    TAB_RNG,
    ICON_TAB,
    FOREMAN_TAB,
    MAC_POOL_TAB,
    IPV4_TAB,
    IPV6_TAB,
    QOS_TAB,
    KERNEL_TAB,
    HOSTED_ENGINE,
    AFFINITY_TAB
}
