CREATE SEQUENCE audit_log_seq INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE custom_actions_seq INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE schema_version_seq INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE vdc_db_log_seq INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE vdc_options_seq INCREMENT BY 1 START WITH 1;
