.TH engine\-upgrade 8 "September 4, 2012" "3.3.0"
.SH NAME
engine\-upgrade \- Upgrade utility for Red Hat Enterprise Virtualization
Manager.
.SH SYNOPSIS
engine\-upgrade [options]
.SH DESCRIPTION
The engine\-upgrade utility is used to upgrade the Red Hat Enterprise
Virtualization Manager. This utility is built on top of yum to provide
extra validation and rollback capabilities.
.SH GENERAL OPTIONS
.TP
\-h, \-\-help
Show help information and exit.
.TP
\-r, \-\-no\-yum\-rollback
Do not rollback yum transaction in case of a failure.
.TP
\-u, \-\-unattended
Perform unattended upgrade, stopping the JBoss service before upgrading.
.TP
\-s, \-\-force\-current\-setup\-rpm
Perform upgrade with the currently installed engine\-setup package, even
when a newer version of that package is available.
.TP
\-c, \-\-check\-updates
Check for updated packages but do not install them.
.SH BUGS
Report bugs at https://bugzilla.redhat.com/.
