//package org.ovirt.engine.core.bll;
//
//import static org.mockito.Mockito.atLeastOnce;
//import static org.mockito.Mockito.verify;
//
//import org.junit.Ignore;
//import org.junit.Test;
//import org.ovirt.engine.core.common.interfaces.SearchType;
//import org.ovirt.engine.core.common.queries.SearchParameters;
//
//public class DirectoryUserSearchQueryTest extends DirectorySearchQueryTestBase {
//    // The name of the user to search:
//    private static final String NAME = "gandalf";
//
//    /**
//     * The objective of this test is to verify that the LDAP filter generated by the {@link SearchQuery} class is
//     * correct, the success or failure and the result of the command aren't relevant.
//     */
//    @Test
//    @Ignore
//    // TODO: This test should be revisited and fixed
//    public void testFilterGeneration() {
//        // Run the query:
//        SearchParameters parameters = new SearchParameters("AdUser: allnames=" + NAME, SearchType.DirectoryUser);
//        SearchQuery query = new SearchQuery(parameters);
//        query.setInternalExecution(true);
//        query.execute();
//
//        // Check that the directory was used to perform the expected LDAP query:
//        String expectedFilter =
//            "(&($USER_ACCOUNT_TYPE) (|" +
//                "($GIVENNAME=" + NAME + ")" +
//                "(sn=" + NAME + ")" +
//                "($USER_ACCOUNT_NAME=" + NAME + ")" +
//                "($PRINCIPAL_NAME=" + NAME + ")" +
//            "))";
//        verify(authzMock, atLeastOnce()).queryUsers(expectedFilter);
//    }
// }
