select fn_db_delete_config_value_all_versions('PackageNamesForCheckUpdate');
select fn_db_delete_config_value_all_versions('UserPackageNamesForCheckUpdate');
select fn_db_delete_config_value_all_versions('OvirtNodePackageNamesForCheckUpdate');
