select fn_db_delete_config_value_all_versions('DnsResolverConfigurationSupported');
select fn_db_delete_config_value_all_versions('LogMaxSwapUsedThresholdInPercentage');
select fn_db_delete_config_value_all_versions('LogMinFreeSwapThresholdInMB');
