UPDATE audit_log
SET deleted = true
WHERE log_type IN (
  920, --NETWORK_ATTACH_NETWORK_TO_VDS
  921, --NETWORK_ATTACH_NETWORK_TO_VDS_FAILED
  922, --NETWORK_DETACH_NETWORK_FROM_VDS
  923, --NETWORK_DETACH_NETWORK_FROM_VDS_FAILED
  924, --NETWORK_ADD_BOND
  925  --NETWORK_ADD_BOND_FAILED
);
